// Code generated by ent, DO NOT EDIT.

package split

import (
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the split type in the database.
	Label = "split"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldUserID holds the string denoting the user_id field in the database.
	FieldUserID = "user_id"
	// FieldAmount holds the string denoting the amount field in the database.
	FieldAmount = "amount"
	// FieldSettled holds the string denoting the settled field in the database.
	FieldSettled = "settled"
	// EdgeExpense holds the string denoting the expense edge name in mutations.
	EdgeExpense = "expense"
	// Table holds the table name of the split in the database.
	Table = "splits"
	// ExpenseTable is the table that holds the expense relation/edge.
	ExpenseTable = "splits"
	// ExpenseInverseTable is the table name for the Expense entity.
	// It exists in this package in order to avoid circular dependency with the "expense" package.
	ExpenseInverseTable = "expenses"
	// ExpenseColumn is the table column denoting the expense relation/edge.
	ExpenseColumn = "expense_splits"
)

// Columns holds all SQL columns for split fields.
var Columns = []string{
	FieldID,
	FieldUserID,
	FieldAmount,
	FieldSettled,
}

// ForeignKeys holds the SQL foreign-keys that are owned by the "splits"
// table and are not defined as standalone fields in the schema.
var ForeignKeys = []string{
	"expense_splits",
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	for i := range ForeignKeys {
		if column == ForeignKeys[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultSettled holds the default value on creation for the "settled" field.
	DefaultSettled bool
)

// OrderOption defines the ordering options for the Split queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByUserID orders the results by the user_id field.
func ByUserID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUserID, opts...).ToFunc()
}

// ByAmount orders the results by the amount field.
func ByAmount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAmount, opts...).ToFunc()
}

// BySettled orders the results by the settled field.
func BySettled(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSettled, opts...).ToFunc()
}

// ByExpenseField orders the results by expense field.
func ByExpenseField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newExpenseStep(), sql.OrderByField(field, opts...))
	}
}
func newExpenseStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(ExpenseInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, ExpenseTable, ExpenseColumn),
	)
}
