// Code generated by ent, DO NOT EDIT.

package expense

import (
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the expense type in the database.
	Label = "expense"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldAmount holds the string denoting the amount field in the database.
	FieldAmount = "amount"
	// FieldCurrency holds the string denoting the currency field in the database.
	FieldCurrency = "currency"
	// FieldDescription holds the string denoting the description field in the database.
	FieldDescription = "description"
	// FieldPayerID holds the string denoting the payer_id field in the database.
	FieldPayerID = "payer_id"
	// FieldType holds the string denoting the type field in the database.
	FieldType = "type"
	// FieldDeleted holds the string denoting the deleted field in the database.
	FieldDeleted = "deleted"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// EdgeLedger holds the string denoting the ledger edge name in mutations.
	EdgeLedger = "ledger"
	// EdgeSplits holds the string denoting the splits edge name in mutations.
	EdgeSplits = "splits"
	// Table holds the table name of the expense in the database.
	Table = "expenses"
	// LedgerTable is the table that holds the ledger relation/edge.
	LedgerTable = "expenses"
	// LedgerInverseTable is the table name for the Ledger entity.
	// It exists in this package in order to avoid circular dependency with the "ledger" package.
	LedgerInverseTable = "ledgers"
	// LedgerColumn is the table column denoting the ledger relation/edge.
	LedgerColumn = "ledger_expenses"
	// SplitsTable is the table that holds the splits relation/edge.
	SplitsTable = "splits"
	// SplitsInverseTable is the table name for the Split entity.
	// It exists in this package in order to avoid circular dependency with the "split" package.
	SplitsInverseTable = "splits"
	// SplitsColumn is the table column denoting the splits relation/edge.
	SplitsColumn = "expense_splits"
)

// Columns holds all SQL columns for expense fields.
var Columns = []string{
	FieldID,
	FieldAmount,
	FieldCurrency,
	FieldDescription,
	FieldPayerID,
	FieldType,
	FieldDeleted,
	FieldCreatedAt,
}

// ForeignKeys holds the SQL foreign-keys that are owned by the "expenses"
// table and are not defined as standalone fields in the schema.
var ForeignKeys = []string{
	"ledger_expenses",
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	for i := range ForeignKeys {
		if column == ForeignKeys[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCurrency holds the default value on creation for the "currency" field.
	DefaultCurrency string
	// DefaultDeleted holds the default value on creation for the "deleted" field.
	DefaultDeleted bool
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
)

// Type defines the type for the "type" enum field.
type Type string

// Type values.
const (
	TypeSplit Type = "split"
	TypeFor   Type = "for"
)

func (_type Type) String() string {
	return string(_type)
}

// TypeValidator is a validator for the "type" field enum values. It is called by the builders before save.
func TypeValidator(_type Type) error {
	switch _type {
	case TypeSplit, TypeFor:
		return nil
	default:
		return fmt.Errorf("expense: invalid enum value for type field: %q", _type)
	}
}

// OrderOption defines the ordering options for the Expense queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByAmount orders the results by the amount field.
func ByAmount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAmount, opts...).ToFunc()
}

// ByCurrency orders the results by the currency field.
func ByCurrency(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCurrency, opts...).ToFunc()
}

// ByDescription orders the results by the description field.
func ByDescription(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDescription, opts...).ToFunc()
}

// ByPayerID orders the results by the payer_id field.
func ByPayerID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPayerID, opts...).ToFunc()
}

// ByType orders the results by the type field.
func ByType(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldType, opts...).ToFunc()
}

// ByDeleted orders the results by the deleted field.
func ByDeleted(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDeleted, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByLedgerField orders the results by ledger field.
func ByLedgerField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newLedgerStep(), sql.OrderByField(field, opts...))
	}
}

// BySplitsCount orders the results by splits count.
func BySplitsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newSplitsStep(), opts...)
	}
}

// BySplits orders the results by splits terms.
func BySplits(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newSplitsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newLedgerStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(LedgerInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, LedgerTable, LedgerColumn),
	)
}
func newSplitsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(SplitsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, SplitsTable, SplitsColumn),
	)
}
