// Code generated by ent, DO NOT EDIT.

package expense

import (
	"bill-bot/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.Expense {
	return predicate.Expense(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.Expense {
	return predicate.Expense(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.Expense {
	return predicate.Expense(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.Expense {
	return predicate.Expense(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.Expense {
	return predicate.Expense(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.Expense {
	return predicate.Expense(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.Expense {
	return predicate.Expense(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.Expense {
	return predicate.Expense(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.Expense {
	return predicate.Expense(sql.FieldLTE(FieldID, id))
}

// Amount applies equality check predicate on the "amount" field. It's identical to AmountEQ.
func Amount(v int64) predicate.Expense {
	return predicate.Expense(sql.FieldEQ(FieldAmount, v))
}

// Currency applies equality check predicate on the "currency" field. It's identical to CurrencyEQ.
func Currency(v string) predicate.Expense {
	return predicate.Expense(sql.FieldEQ(FieldCurrency, v))
}

// Description applies equality check predicate on the "description" field. It's identical to DescriptionEQ.
func Description(v string) predicate.Expense {
	return predicate.Expense(sql.FieldEQ(FieldDescription, v))
}

// PayerID applies equality check predicate on the "payer_id" field. It's identical to PayerIDEQ.
func PayerID(v string) predicate.Expense {
	return predicate.Expense(sql.FieldEQ(FieldPayerID, v))
}

// Deleted applies equality check predicate on the "deleted" field. It's identical to DeletedEQ.
func Deleted(v bool) predicate.Expense {
	return predicate.Expense(sql.FieldEQ(FieldDeleted, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.Expense {
	return predicate.Expense(sql.FieldEQ(FieldCreatedAt, v))
}

// AmountEQ applies the EQ predicate on the "amount" field.
func AmountEQ(v int64) predicate.Expense {
	return predicate.Expense(sql.FieldEQ(FieldAmount, v))
}

// AmountNEQ applies the NEQ predicate on the "amount" field.
func AmountNEQ(v int64) predicate.Expense {
	return predicate.Expense(sql.FieldNEQ(FieldAmount, v))
}

// AmountIn applies the In predicate on the "amount" field.
func AmountIn(vs ...int64) predicate.Expense {
	return predicate.Expense(sql.FieldIn(FieldAmount, vs...))
}

// AmountNotIn applies the NotIn predicate on the "amount" field.
func AmountNotIn(vs ...int64) predicate.Expense {
	return predicate.Expense(sql.FieldNotIn(FieldAmount, vs...))
}

// AmountGT applies the GT predicate on the "amount" field.
func AmountGT(v int64) predicate.Expense {
	return predicate.Expense(sql.FieldGT(FieldAmount, v))
}

// AmountGTE applies the GTE predicate on the "amount" field.
func AmountGTE(v int64) predicate.Expense {
	return predicate.Expense(sql.FieldGTE(FieldAmount, v))
}

// AmountLT applies the LT predicate on the "amount" field.
func AmountLT(v int64) predicate.Expense {
	return predicate.Expense(sql.FieldLT(FieldAmount, v))
}

// AmountLTE applies the LTE predicate on the "amount" field.
func AmountLTE(v int64) predicate.Expense {
	return predicate.Expense(sql.FieldLTE(FieldAmount, v))
}

// CurrencyEQ applies the EQ predicate on the "currency" field.
func CurrencyEQ(v string) predicate.Expense {
	return predicate.Expense(sql.FieldEQ(FieldCurrency, v))
}

// CurrencyNEQ applies the NEQ predicate on the "currency" field.
func CurrencyNEQ(v string) predicate.Expense {
	return predicate.Expense(sql.FieldNEQ(FieldCurrency, v))
}

// CurrencyIn applies the In predicate on the "currency" field.
func CurrencyIn(vs ...string) predicate.Expense {
	return predicate.Expense(sql.FieldIn(FieldCurrency, vs...))
}

// CurrencyNotIn applies the NotIn predicate on the "currency" field.
func CurrencyNotIn(vs ...string) predicate.Expense {
	return predicate.Expense(sql.FieldNotIn(FieldCurrency, vs...))
}

// CurrencyGT applies the GT predicate on the "currency" field.
func CurrencyGT(v string) predicate.Expense {
	return predicate.Expense(sql.FieldGT(FieldCurrency, v))
}

// CurrencyGTE applies the GTE predicate on the "currency" field.
func CurrencyGTE(v string) predicate.Expense {
	return predicate.Expense(sql.FieldGTE(FieldCurrency, v))
}

// CurrencyLT applies the LT predicate on the "currency" field.
func CurrencyLT(v string) predicate.Expense {
	return predicate.Expense(sql.FieldLT(FieldCurrency, v))
}

// CurrencyLTE applies the LTE predicate on the "currency" field.
func CurrencyLTE(v string) predicate.Expense {
	return predicate.Expense(sql.FieldLTE(FieldCurrency, v))
}

// CurrencyContains applies the Contains predicate on the "currency" field.
func CurrencyContains(v string) predicate.Expense {
	return predicate.Expense(sql.FieldContains(FieldCurrency, v))
}

// CurrencyHasPrefix applies the HasPrefix predicate on the "currency" field.
func CurrencyHasPrefix(v string) predicate.Expense {
	return predicate.Expense(sql.FieldHasPrefix(FieldCurrency, v))
}

// CurrencyHasSuffix applies the HasSuffix predicate on the "currency" field.
func CurrencyHasSuffix(v string) predicate.Expense {
	return predicate.Expense(sql.FieldHasSuffix(FieldCurrency, v))
}

// CurrencyEqualFold applies the EqualFold predicate on the "currency" field.
func CurrencyEqualFold(v string) predicate.Expense {
	return predicate.Expense(sql.FieldEqualFold(FieldCurrency, v))
}

// CurrencyContainsFold applies the ContainsFold predicate on the "currency" field.
func CurrencyContainsFold(v string) predicate.Expense {
	return predicate.Expense(sql.FieldContainsFold(FieldCurrency, v))
}

// DescriptionEQ applies the EQ predicate on the "description" field.
func DescriptionEQ(v string) predicate.Expense {
	return predicate.Expense(sql.FieldEQ(FieldDescription, v))
}

// DescriptionNEQ applies the NEQ predicate on the "description" field.
func DescriptionNEQ(v string) predicate.Expense {
	return predicate.Expense(sql.FieldNEQ(FieldDescription, v))
}

// DescriptionIn applies the In predicate on the "description" field.
func DescriptionIn(vs ...string) predicate.Expense {
	return predicate.Expense(sql.FieldIn(FieldDescription, vs...))
}

// DescriptionNotIn applies the NotIn predicate on the "description" field.
func DescriptionNotIn(vs ...string) predicate.Expense {
	return predicate.Expense(sql.FieldNotIn(FieldDescription, vs...))
}

// DescriptionGT applies the GT predicate on the "description" field.
func DescriptionGT(v string) predicate.Expense {
	return predicate.Expense(sql.FieldGT(FieldDescription, v))
}

// DescriptionGTE applies the GTE predicate on the "description" field.
func DescriptionGTE(v string) predicate.Expense {
	return predicate.Expense(sql.FieldGTE(FieldDescription, v))
}

// DescriptionLT applies the LT predicate on the "description" field.
func DescriptionLT(v string) predicate.Expense {
	return predicate.Expense(sql.FieldLT(FieldDescription, v))
}

// DescriptionLTE applies the LTE predicate on the "description" field.
func DescriptionLTE(v string) predicate.Expense {
	return predicate.Expense(sql.FieldLTE(FieldDescription, v))
}

// DescriptionContains applies the Contains predicate on the "description" field.
func DescriptionContains(v string) predicate.Expense {
	return predicate.Expense(sql.FieldContains(FieldDescription, v))
}

// DescriptionHasPrefix applies the HasPrefix predicate on the "description" field.
func DescriptionHasPrefix(v string) predicate.Expense {
	return predicate.Expense(sql.FieldHasPrefix(FieldDescription, v))
}

// DescriptionHasSuffix applies the HasSuffix predicate on the "description" field.
func DescriptionHasSuffix(v string) predicate.Expense {
	return predicate.Expense(sql.FieldHasSuffix(FieldDescription, v))
}

// DescriptionEqualFold applies the EqualFold predicate on the "description" field.
func DescriptionEqualFold(v string) predicate.Expense {
	return predicate.Expense(sql.FieldEqualFold(FieldDescription, v))
}

// DescriptionContainsFold applies the ContainsFold predicate on the "description" field.
func DescriptionContainsFold(v string) predicate.Expense {
	return predicate.Expense(sql.FieldContainsFold(FieldDescription, v))
}

// PayerIDEQ applies the EQ predicate on the "payer_id" field.
func PayerIDEQ(v string) predicate.Expense {
	return predicate.Expense(sql.FieldEQ(FieldPayerID, v))
}

// PayerIDNEQ applies the NEQ predicate on the "payer_id" field.
func PayerIDNEQ(v string) predicate.Expense {
	return predicate.Expense(sql.FieldNEQ(FieldPayerID, v))
}

// PayerIDIn applies the In predicate on the "payer_id" field.
func PayerIDIn(vs ...string) predicate.Expense {
	return predicate.Expense(sql.FieldIn(FieldPayerID, vs...))
}

// PayerIDNotIn applies the NotIn predicate on the "payer_id" field.
func PayerIDNotIn(vs ...string) predicate.Expense {
	return predicate.Expense(sql.FieldNotIn(FieldPayerID, vs...))
}

// PayerIDGT applies the GT predicate on the "payer_id" field.
func PayerIDGT(v string) predicate.Expense {
	return predicate.Expense(sql.FieldGT(FieldPayerID, v))
}

// PayerIDGTE applies the GTE predicate on the "payer_id" field.
func PayerIDGTE(v string) predicate.Expense {
	return predicate.Expense(sql.FieldGTE(FieldPayerID, v))
}

// PayerIDLT applies the LT predicate on the "payer_id" field.
func PayerIDLT(v string) predicate.Expense {
	return predicate.Expense(sql.FieldLT(FieldPayerID, v))
}

// PayerIDLTE applies the LTE predicate on the "payer_id" field.
func PayerIDLTE(v string) predicate.Expense {
	return predicate.Expense(sql.FieldLTE(FieldPayerID, v))
}

// PayerIDContains applies the Contains predicate on the "payer_id" field.
func PayerIDContains(v string) predicate.Expense {
	return predicate.Expense(sql.FieldContains(FieldPayerID, v))
}

// PayerIDHasPrefix applies the HasPrefix predicate on the "payer_id" field.
func PayerIDHasPrefix(v string) predicate.Expense {
	return predicate.Expense(sql.FieldHasPrefix(FieldPayerID, v))
}

// PayerIDHasSuffix applies the HasSuffix predicate on the "payer_id" field.
func PayerIDHasSuffix(v string) predicate.Expense {
	return predicate.Expense(sql.FieldHasSuffix(FieldPayerID, v))
}

// PayerIDEqualFold applies the EqualFold predicate on the "payer_id" field.
func PayerIDEqualFold(v string) predicate.Expense {
	return predicate.Expense(sql.FieldEqualFold(FieldPayerID, v))
}

// PayerIDContainsFold applies the ContainsFold predicate on the "payer_id" field.
func PayerIDContainsFold(v string) predicate.Expense {
	return predicate.Expense(sql.FieldContainsFold(FieldPayerID, v))
}

// TypeEQ applies the EQ predicate on the "type" field.
func TypeEQ(v Type) predicate.Expense {
	return predicate.Expense(sql.FieldEQ(FieldType, v))
}

// TypeNEQ applies the NEQ predicate on the "type" field.
func TypeNEQ(v Type) predicate.Expense {
	return predicate.Expense(sql.FieldNEQ(FieldType, v))
}

// TypeIn applies the In predicate on the "type" field.
func TypeIn(vs ...Type) predicate.Expense {
	return predicate.Expense(sql.FieldIn(FieldType, vs...))
}

// TypeNotIn applies the NotIn predicate on the "type" field.
func TypeNotIn(vs ...Type) predicate.Expense {
	return predicate.Expense(sql.FieldNotIn(FieldType, vs...))
}

// DeletedEQ applies the EQ predicate on the "deleted" field.
func DeletedEQ(v bool) predicate.Expense {
	return predicate.Expense(sql.FieldEQ(FieldDeleted, v))
}

// DeletedNEQ applies the NEQ predicate on the "deleted" field.
func DeletedNEQ(v bool) predicate.Expense {
	return predicate.Expense(sql.FieldNEQ(FieldDeleted, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.Expense {
	return predicate.Expense(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.Expense {
	return predicate.Expense(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.Expense {
	return predicate.Expense(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.Expense {
	return predicate.Expense(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.Expense {
	return predicate.Expense(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.Expense {
	return predicate.Expense(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.Expense {
	return predicate.Expense(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.Expense {
	return predicate.Expense(sql.FieldLTE(FieldCreatedAt, v))
}

// HasLedger applies the HasEdge predicate on the "ledger" edge.
func HasLedger() predicate.Expense {
	return predicate.Expense(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, LedgerTable, LedgerColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasLedgerWith applies the HasEdge predicate on the "ledger" edge with a given conditions (other predicates).
func HasLedgerWith(preds ...predicate.Ledger) predicate.Expense {
	return predicate.Expense(func(s *sql.Selector) {
		step := newLedgerStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasSplits applies the HasEdge predicate on the "splits" edge.
func HasSplits() predicate.Expense {
	return predicate.Expense(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, SplitsTable, SplitsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasSplitsWith applies the HasEdge predicate on the "splits" edge with a given conditions (other predicates).
func HasSplitsWith(preds ...predicate.Split) predicate.Expense {
	return predicate.Expense(func(s *sql.Selector) {
		step := newSplitsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Expense) predicate.Expense {
	return predicate.Expense(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Expense) predicate.Expense {
	return predicate.Expense(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Expense) predicate.Expense {
	return predicate.Expense(sql.NotPredicates(p))
}
