// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// ExpensesColumns holds the columns for the "expenses" table.
	ExpensesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "amount", Type: field.TypeInt64},
		{Name: "currency", Type: field.TypeString, Default: "TWD"},
		{Name: "description", Type: field.TypeString},
		{Name: "payer_id", Type: field.TypeString},
		{Name: "type", Type: field.TypeEnum, Enums: []string{"split", "for"}},
		{Name: "deleted", Type: field.TypeBool, Default: false},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "ledger_expenses", Type: field.TypeInt},
	}
	// ExpensesTable holds the schema information for the "expenses" table.
	ExpensesTable = &schema.Table{
		Name:       "expenses",
		Columns:    ExpensesColumns,
		PrimaryKey: []*schema.Column{ExpensesColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "expenses_ledgers_expenses",
				Columns:    []*schema.Column{ExpensesColumns[8]},
				RefColumns: []*schema.Column{LedgersColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
	}
	// LedgersColumns holds the columns for the "ledgers" table.
	LedgersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "channel_id", Type: field.TypeString, Unique: true},
		{Name: "guild_id", Type: field.TypeString},
		{Name: "category_id", Type: field.TypeString, Nullable: true},
		{Name: "pinned_message_id", Type: field.TypeString, Nullable: true},
		{Name: "active", Type: field.TypeBool, Default: true},
		{Name: "created_at", Type: field.TypeTime},
	}
	// LedgersTable holds the schema information for the "ledgers" table.
	LedgersTable = &schema.Table{
		Name:       "ledgers",
		Columns:    LedgersColumns,
		PrimaryKey: []*schema.Column{LedgersColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "ledger_guild_id",
				Unique:  false,
				Columns: []*schema.Column{LedgersColumns[2]},
			},
			{
				Name:    "ledger_guild_id_channel_id",
				Unique:  false,
				Columns: []*schema.Column{LedgersColumns[2], LedgersColumns[1]},
			},
		},
	}
	// LedgerMembersColumns holds the columns for the "ledger_members" table.
	LedgerMembersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "user_id", Type: field.TypeString},
		{Name: "user_name", Type: field.TypeString},
		{Name: "active", Type: field.TypeBool, Default: true},
		{Name: "joined_at", Type: field.TypeTime},
		{Name: "ledger_members", Type: field.TypeInt},
	}
	// LedgerMembersTable holds the schema information for the "ledger_members" table.
	LedgerMembersTable = &schema.Table{
		Name:       "ledger_members",
		Columns:    LedgerMembersColumns,
		PrimaryKey: []*schema.Column{LedgerMembersColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "ledger_members_ledgers_members",
				Columns:    []*schema.Column{LedgerMembersColumns[5]},
				RefColumns: []*schema.Column{LedgersColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "ledgermember_user_id_ledger_members",
				Unique:  true,
				Columns: []*schema.Column{LedgerMembersColumns[1], LedgerMembersColumns[5]},
			},
		},
	}
	// PaymentsColumns holds the columns for the "payments" table.
	PaymentsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "from_user_id", Type: field.TypeString},
		{Name: "from_user_name", Type: field.TypeString},
		{Name: "to_user_id", Type: field.TypeString},
		{Name: "to_user_name", Type: field.TypeString},
		{Name: "amount", Type: field.TypeInt64},
		{Name: "note", Type: field.TypeString, Nullable: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "ledger_payments", Type: field.TypeInt},
	}
	// PaymentsTable holds the schema information for the "payments" table.
	PaymentsTable = &schema.Table{
		Name:       "payments",
		Columns:    PaymentsColumns,
		PrimaryKey: []*schema.Column{PaymentsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "payments_ledgers_payments",
				Columns:    []*schema.Column{PaymentsColumns[8]},
				RefColumns: []*schema.Column{LedgersColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
	}
	// SplitsColumns holds the columns for the "splits" table.
	SplitsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "user_id", Type: field.TypeString},
		{Name: "amount", Type: field.TypeInt64},
		{Name: "settled", Type: field.TypeBool, Default: false},
		{Name: "expense_splits", Type: field.TypeInt},
	}
	// SplitsTable holds the schema information for the "splits" table.
	SplitsTable = &schema.Table{
		Name:       "splits",
		Columns:    SplitsColumns,
		PrimaryKey: []*schema.Column{SplitsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "splits_expenses_splits",
				Columns:    []*schema.Column{SplitsColumns[4]},
				RefColumns: []*schema.Column{ExpensesColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		ExpensesTable,
		LedgersTable,
		LedgerMembersTable,
		PaymentsTable,
		SplitsTable,
	}
)

func init() {
	ExpensesTable.ForeignKeys[0].RefTable = LedgersTable
	LedgerMembersTable.ForeignKeys[0].RefTable = LedgersTable
	PaymentsTable.ForeignKeys[0].RefTable = LedgersTable
	SplitsTable.ForeignKeys[0].RefTable = ExpensesTable
}
