// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"log"
	"reflect"

	"bill-bot/ent/migrate"

	"bill-bot/ent/expense"
	"bill-bot/ent/ledger"
	"bill-bot/ent/ledgermember"
	"bill-bot/ent/payment"
	"bill-bot/ent/split"

	"entgo.io/ent"
	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

// Client is the client that holds all ent builders.
type Client struct {
	config
	// Schema is the client for creating, migrating and dropping schema.
	Schema *migrate.Schema
	// Expense is the client for interacting with the Expense builders.
	Expense *ExpenseClient
	// Ledger is the client for interacting with the Ledger builders.
	Ledger *LedgerClient
	// LedgerMember is the client for interacting with the LedgerMember builders.
	LedgerMember *LedgerMemberClient
	// Payment is the client for interacting with the Payment builders.
	Payment *PaymentClient
	// Split is the client for interacting with the Split builders.
	Split *SplitClient
}

// NewClient creates a new client configured with the given options.
func NewClient(opts ...Option) *Client {
	client := &Client{config: newConfig(opts...)}
	client.init()
	return client
}

func (c *Client) init() {
	c.Schema = migrate.NewSchema(c.driver)
	c.Expense = NewExpenseClient(c.config)
	c.Ledger = NewLedgerClient(c.config)
	c.LedgerMember = NewLedgerMemberClient(c.config)
	c.Payment = NewPaymentClient(c.config)
	c.Split = NewSplitClient(c.config)
}

type (
	// config is the configuration for the client and its builder.
	config struct {
		// driver used for executing database requests.
		driver dialect.Driver
		// debug enable a debug logging.
		debug bool
		// log used for logging on debug mode.
		log func(...any)
		// hooks to execute on mutations.
		hooks *hooks
		// interceptors to execute on queries.
		inters *inters
	}
	// Option function to configure the client.
	Option func(*config)
)

// newConfig creates a new config for the client.
func newConfig(opts ...Option) config {
	cfg := config{log: log.Println, hooks: &hooks{}, inters: &inters{}}
	cfg.options(opts...)
	return cfg
}

// options applies the options on the config object.
func (c *config) options(opts ...Option) {
	for _, opt := range opts {
		opt(c)
	}
	if c.debug {
		c.driver = dialect.Debug(c.driver, c.log)
	}
}

// Debug enables debug logging on the ent.Driver.
func Debug() Option {
	return func(c *config) {
		c.debug = true
	}
}

// Log sets the logging function for debug mode.
func Log(fn func(...any)) Option {
	return func(c *config) {
		c.log = fn
	}
}

// Driver configures the client driver.
func Driver(driver dialect.Driver) Option {
	return func(c *config) {
		c.driver = driver
	}
}

// Open opens a database/sql.DB specified by the driver name and
// the data source name, and returns a new client attached to it.
// Optional parameters can be added for configuring the client.
func Open(driverName, dataSourceName string, options ...Option) (*Client, error) {
	switch driverName {
	case dialect.MySQL, dialect.Postgres, dialect.SQLite:
		drv, err := sql.Open(driverName, dataSourceName)
		if err != nil {
			return nil, err
		}
		return NewClient(append(options, Driver(drv))...), nil
	default:
		return nil, fmt.Errorf("unsupported driver: %q", driverName)
	}
}

// ErrTxStarted is returned when trying to start a new transaction from a transactional client.
var ErrTxStarted = errors.New("ent: cannot start a transaction within a transaction")

// Tx returns a new transactional client. The provided context
// is used until the transaction is committed or rolled back.
func (c *Client) Tx(ctx context.Context) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, ErrTxStarted
	}
	tx, err := newTx(ctx, c.driver)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = tx
	return &Tx{
		ctx:          ctx,
		config:       cfg,
		Expense:      NewExpenseClient(cfg),
		Ledger:       NewLedgerClient(cfg),
		LedgerMember: NewLedgerMemberClient(cfg),
		Payment:      NewPaymentClient(cfg),
		Split:        NewSplitClient(cfg),
	}, nil
}

// BeginTx returns a transactional client with specified options.
func (c *Client) BeginTx(ctx context.Context, opts *sql.TxOptions) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, errors.New("ent: cannot start a transaction within a transaction")
	}
	tx, err := c.driver.(interface {
		BeginTx(context.Context, *sql.TxOptions) (dialect.Tx, error)
	}).BeginTx(ctx, opts)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = &txDriver{tx: tx, drv: c.driver}
	return &Tx{
		ctx:          ctx,
		config:       cfg,
		Expense:      NewExpenseClient(cfg),
		Ledger:       NewLedgerClient(cfg),
		LedgerMember: NewLedgerMemberClient(cfg),
		Payment:      NewPaymentClient(cfg),
		Split:        NewSplitClient(cfg),
	}, nil
}

// Debug returns a new debug-client. It's used to get verbose logging on specific operations.
//
//	client.Debug().
//		Expense.
//		Query().
//		Count(ctx)
func (c *Client) Debug() *Client {
	if c.debug {
		return c
	}
	cfg := c.config
	cfg.driver = dialect.Debug(c.driver, c.log)
	client := &Client{config: cfg}
	client.init()
	return client
}

// Close closes the database connection and prevents new queries from starting.
func (c *Client) Close() error {
	return c.driver.Close()
}

// Use adds the mutation hooks to all the entity clients.
// In order to add hooks to a specific client, call: `client.Node.Use(...)`.
func (c *Client) Use(hooks ...Hook) {
	c.Expense.Use(hooks...)
	c.Ledger.Use(hooks...)
	c.LedgerMember.Use(hooks...)
	c.Payment.Use(hooks...)
	c.Split.Use(hooks...)
}

// Intercept adds the query interceptors to all the entity clients.
// In order to add interceptors to a specific client, call: `client.Node.Intercept(...)`.
func (c *Client) Intercept(interceptors ...Interceptor) {
	c.Expense.Intercept(interceptors...)
	c.Ledger.Intercept(interceptors...)
	c.LedgerMember.Intercept(interceptors...)
	c.Payment.Intercept(interceptors...)
	c.Split.Intercept(interceptors...)
}

// Mutate implements the ent.Mutator interface.
func (c *Client) Mutate(ctx context.Context, m Mutation) (Value, error) {
	switch m := m.(type) {
	case *ExpenseMutation:
		return c.Expense.mutate(ctx, m)
	case *LedgerMutation:
		return c.Ledger.mutate(ctx, m)
	case *LedgerMemberMutation:
		return c.LedgerMember.mutate(ctx, m)
	case *PaymentMutation:
		return c.Payment.mutate(ctx, m)
	case *SplitMutation:
		return c.Split.mutate(ctx, m)
	default:
		return nil, fmt.Errorf("ent: unknown mutation type %T", m)
	}
}

// ExpenseClient is a client for the Expense schema.
type ExpenseClient struct {
	config
}

// NewExpenseClient returns a client for the Expense from the given config.
func NewExpenseClient(c config) *ExpenseClient {
	return &ExpenseClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `expense.Hooks(f(g(h())))`.
func (c *ExpenseClient) Use(hooks ...Hook) {
	c.hooks.Expense = append(c.hooks.Expense, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `expense.Intercept(f(g(h())))`.
func (c *ExpenseClient) Intercept(interceptors ...Interceptor) {
	c.inters.Expense = append(c.inters.Expense, interceptors...)
}

// Create returns a builder for creating a Expense entity.
func (c *ExpenseClient) Create() *ExpenseCreate {
	mutation := newExpenseMutation(c.config, OpCreate)
	return &ExpenseCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of Expense entities.
func (c *ExpenseClient) CreateBulk(builders ...*ExpenseCreate) *ExpenseCreateBulk {
	return &ExpenseCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *ExpenseClient) MapCreateBulk(slice any, setFunc func(*ExpenseCreate, int)) *ExpenseCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &ExpenseCreateBulk{err: fmt.Errorf("calling to ExpenseClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*ExpenseCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &ExpenseCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for Expense.
func (c *ExpenseClient) Update() *ExpenseUpdate {
	mutation := newExpenseMutation(c.config, OpUpdate)
	return &ExpenseUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *ExpenseClient) UpdateOne(_m *Expense) *ExpenseUpdateOne {
	mutation := newExpenseMutation(c.config, OpUpdateOne, withExpense(_m))
	return &ExpenseUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *ExpenseClient) UpdateOneID(id int) *ExpenseUpdateOne {
	mutation := newExpenseMutation(c.config, OpUpdateOne, withExpenseID(id))
	return &ExpenseUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for Expense.
func (c *ExpenseClient) Delete() *ExpenseDelete {
	mutation := newExpenseMutation(c.config, OpDelete)
	return &ExpenseDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *ExpenseClient) DeleteOne(_m *Expense) *ExpenseDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *ExpenseClient) DeleteOneID(id int) *ExpenseDeleteOne {
	builder := c.Delete().Where(expense.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &ExpenseDeleteOne{builder}
}

// Query returns a query builder for Expense.
func (c *ExpenseClient) Query() *ExpenseQuery {
	return &ExpenseQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeExpense},
		inters: c.Interceptors(),
	}
}

// Get returns a Expense entity by its id.
func (c *ExpenseClient) Get(ctx context.Context, id int) (*Expense, error) {
	return c.Query().Where(expense.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *ExpenseClient) GetX(ctx context.Context, id int) *Expense {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryLedger queries the ledger edge of a Expense.
func (c *ExpenseClient) QueryLedger(_m *Expense) *LedgerQuery {
	query := (&LedgerClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(expense.Table, expense.FieldID, id),
			sqlgraph.To(ledger.Table, ledger.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, expense.LedgerTable, expense.LedgerColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QuerySplits queries the splits edge of a Expense.
func (c *ExpenseClient) QuerySplits(_m *Expense) *SplitQuery {
	query := (&SplitClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(expense.Table, expense.FieldID, id),
			sqlgraph.To(split.Table, split.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, expense.SplitsTable, expense.SplitsColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *ExpenseClient) Hooks() []Hook {
	return c.hooks.Expense
}

// Interceptors returns the client interceptors.
func (c *ExpenseClient) Interceptors() []Interceptor {
	return c.inters.Expense
}

func (c *ExpenseClient) mutate(ctx context.Context, m *ExpenseMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&ExpenseCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&ExpenseUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&ExpenseUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&ExpenseDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown Expense mutation op: %q", m.Op())
	}
}

// LedgerClient is a client for the Ledger schema.
type LedgerClient struct {
	config
}

// NewLedgerClient returns a client for the Ledger from the given config.
func NewLedgerClient(c config) *LedgerClient {
	return &LedgerClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `ledger.Hooks(f(g(h())))`.
func (c *LedgerClient) Use(hooks ...Hook) {
	c.hooks.Ledger = append(c.hooks.Ledger, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `ledger.Intercept(f(g(h())))`.
func (c *LedgerClient) Intercept(interceptors ...Interceptor) {
	c.inters.Ledger = append(c.inters.Ledger, interceptors...)
}

// Create returns a builder for creating a Ledger entity.
func (c *LedgerClient) Create() *LedgerCreate {
	mutation := newLedgerMutation(c.config, OpCreate)
	return &LedgerCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of Ledger entities.
func (c *LedgerClient) CreateBulk(builders ...*LedgerCreate) *LedgerCreateBulk {
	return &LedgerCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *LedgerClient) MapCreateBulk(slice any, setFunc func(*LedgerCreate, int)) *LedgerCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &LedgerCreateBulk{err: fmt.Errorf("calling to LedgerClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*LedgerCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &LedgerCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for Ledger.
func (c *LedgerClient) Update() *LedgerUpdate {
	mutation := newLedgerMutation(c.config, OpUpdate)
	return &LedgerUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *LedgerClient) UpdateOne(_m *Ledger) *LedgerUpdateOne {
	mutation := newLedgerMutation(c.config, OpUpdateOne, withLedger(_m))
	return &LedgerUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *LedgerClient) UpdateOneID(id int) *LedgerUpdateOne {
	mutation := newLedgerMutation(c.config, OpUpdateOne, withLedgerID(id))
	return &LedgerUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for Ledger.
func (c *LedgerClient) Delete() *LedgerDelete {
	mutation := newLedgerMutation(c.config, OpDelete)
	return &LedgerDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *LedgerClient) DeleteOne(_m *Ledger) *LedgerDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *LedgerClient) DeleteOneID(id int) *LedgerDeleteOne {
	builder := c.Delete().Where(ledger.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &LedgerDeleteOne{builder}
}

// Query returns a query builder for Ledger.
func (c *LedgerClient) Query() *LedgerQuery {
	return &LedgerQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeLedger},
		inters: c.Interceptors(),
	}
}

// Get returns a Ledger entity by its id.
func (c *LedgerClient) Get(ctx context.Context, id int) (*Ledger, error) {
	return c.Query().Where(ledger.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *LedgerClient) GetX(ctx context.Context, id int) *Ledger {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryExpenses queries the expenses edge of a Ledger.
func (c *LedgerClient) QueryExpenses(_m *Ledger) *ExpenseQuery {
	query := (&ExpenseClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(ledger.Table, ledger.FieldID, id),
			sqlgraph.To(expense.Table, expense.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, ledger.ExpensesTable, ledger.ExpensesColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QueryPayments queries the payments edge of a Ledger.
func (c *LedgerClient) QueryPayments(_m *Ledger) *PaymentQuery {
	query := (&PaymentClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(ledger.Table, ledger.FieldID, id),
			sqlgraph.To(payment.Table, payment.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, ledger.PaymentsTable, ledger.PaymentsColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QueryMembers queries the members edge of a Ledger.
func (c *LedgerClient) QueryMembers(_m *Ledger) *LedgerMemberQuery {
	query := (&LedgerMemberClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(ledger.Table, ledger.FieldID, id),
			sqlgraph.To(ledgermember.Table, ledgermember.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, ledger.MembersTable, ledger.MembersColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *LedgerClient) Hooks() []Hook {
	return c.hooks.Ledger
}

// Interceptors returns the client interceptors.
func (c *LedgerClient) Interceptors() []Interceptor {
	return c.inters.Ledger
}

func (c *LedgerClient) mutate(ctx context.Context, m *LedgerMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&LedgerCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&LedgerUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&LedgerUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&LedgerDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown Ledger mutation op: %q", m.Op())
	}
}

// LedgerMemberClient is a client for the LedgerMember schema.
type LedgerMemberClient struct {
	config
}

// NewLedgerMemberClient returns a client for the LedgerMember from the given config.
func NewLedgerMemberClient(c config) *LedgerMemberClient {
	return &LedgerMemberClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `ledgermember.Hooks(f(g(h())))`.
func (c *LedgerMemberClient) Use(hooks ...Hook) {
	c.hooks.LedgerMember = append(c.hooks.LedgerMember, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `ledgermember.Intercept(f(g(h())))`.
func (c *LedgerMemberClient) Intercept(interceptors ...Interceptor) {
	c.inters.LedgerMember = append(c.inters.LedgerMember, interceptors...)
}

// Create returns a builder for creating a LedgerMember entity.
func (c *LedgerMemberClient) Create() *LedgerMemberCreate {
	mutation := newLedgerMemberMutation(c.config, OpCreate)
	return &LedgerMemberCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of LedgerMember entities.
func (c *LedgerMemberClient) CreateBulk(builders ...*LedgerMemberCreate) *LedgerMemberCreateBulk {
	return &LedgerMemberCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *LedgerMemberClient) MapCreateBulk(slice any, setFunc func(*LedgerMemberCreate, int)) *LedgerMemberCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &LedgerMemberCreateBulk{err: fmt.Errorf("calling to LedgerMemberClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*LedgerMemberCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &LedgerMemberCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for LedgerMember.
func (c *LedgerMemberClient) Update() *LedgerMemberUpdate {
	mutation := newLedgerMemberMutation(c.config, OpUpdate)
	return &LedgerMemberUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *LedgerMemberClient) UpdateOne(_m *LedgerMember) *LedgerMemberUpdateOne {
	mutation := newLedgerMemberMutation(c.config, OpUpdateOne, withLedgerMember(_m))
	return &LedgerMemberUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *LedgerMemberClient) UpdateOneID(id int) *LedgerMemberUpdateOne {
	mutation := newLedgerMemberMutation(c.config, OpUpdateOne, withLedgerMemberID(id))
	return &LedgerMemberUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for LedgerMember.
func (c *LedgerMemberClient) Delete() *LedgerMemberDelete {
	mutation := newLedgerMemberMutation(c.config, OpDelete)
	return &LedgerMemberDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *LedgerMemberClient) DeleteOne(_m *LedgerMember) *LedgerMemberDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *LedgerMemberClient) DeleteOneID(id int) *LedgerMemberDeleteOne {
	builder := c.Delete().Where(ledgermember.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &LedgerMemberDeleteOne{builder}
}

// Query returns a query builder for LedgerMember.
func (c *LedgerMemberClient) Query() *LedgerMemberQuery {
	return &LedgerMemberQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeLedgerMember},
		inters: c.Interceptors(),
	}
}

// Get returns a LedgerMember entity by its id.
func (c *LedgerMemberClient) Get(ctx context.Context, id int) (*LedgerMember, error) {
	return c.Query().Where(ledgermember.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *LedgerMemberClient) GetX(ctx context.Context, id int) *LedgerMember {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryLedger queries the ledger edge of a LedgerMember.
func (c *LedgerMemberClient) QueryLedger(_m *LedgerMember) *LedgerQuery {
	query := (&LedgerClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(ledgermember.Table, ledgermember.FieldID, id),
			sqlgraph.To(ledger.Table, ledger.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, ledgermember.LedgerTable, ledgermember.LedgerColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *LedgerMemberClient) Hooks() []Hook {
	return c.hooks.LedgerMember
}

// Interceptors returns the client interceptors.
func (c *LedgerMemberClient) Interceptors() []Interceptor {
	return c.inters.LedgerMember
}

func (c *LedgerMemberClient) mutate(ctx context.Context, m *LedgerMemberMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&LedgerMemberCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&LedgerMemberUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&LedgerMemberUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&LedgerMemberDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown LedgerMember mutation op: %q", m.Op())
	}
}

// PaymentClient is a client for the Payment schema.
type PaymentClient struct {
	config
}

// NewPaymentClient returns a client for the Payment from the given config.
func NewPaymentClient(c config) *PaymentClient {
	return &PaymentClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `payment.Hooks(f(g(h())))`.
func (c *PaymentClient) Use(hooks ...Hook) {
	c.hooks.Payment = append(c.hooks.Payment, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `payment.Intercept(f(g(h())))`.
func (c *PaymentClient) Intercept(interceptors ...Interceptor) {
	c.inters.Payment = append(c.inters.Payment, interceptors...)
}

// Create returns a builder for creating a Payment entity.
func (c *PaymentClient) Create() *PaymentCreate {
	mutation := newPaymentMutation(c.config, OpCreate)
	return &PaymentCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of Payment entities.
func (c *PaymentClient) CreateBulk(builders ...*PaymentCreate) *PaymentCreateBulk {
	return &PaymentCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *PaymentClient) MapCreateBulk(slice any, setFunc func(*PaymentCreate, int)) *PaymentCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &PaymentCreateBulk{err: fmt.Errorf("calling to PaymentClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*PaymentCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &PaymentCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for Payment.
func (c *PaymentClient) Update() *PaymentUpdate {
	mutation := newPaymentMutation(c.config, OpUpdate)
	return &PaymentUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *PaymentClient) UpdateOne(_m *Payment) *PaymentUpdateOne {
	mutation := newPaymentMutation(c.config, OpUpdateOne, withPayment(_m))
	return &PaymentUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *PaymentClient) UpdateOneID(id int) *PaymentUpdateOne {
	mutation := newPaymentMutation(c.config, OpUpdateOne, withPaymentID(id))
	return &PaymentUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for Payment.
func (c *PaymentClient) Delete() *PaymentDelete {
	mutation := newPaymentMutation(c.config, OpDelete)
	return &PaymentDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *PaymentClient) DeleteOne(_m *Payment) *PaymentDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *PaymentClient) DeleteOneID(id int) *PaymentDeleteOne {
	builder := c.Delete().Where(payment.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &PaymentDeleteOne{builder}
}

// Query returns a query builder for Payment.
func (c *PaymentClient) Query() *PaymentQuery {
	return &PaymentQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypePayment},
		inters: c.Interceptors(),
	}
}

// Get returns a Payment entity by its id.
func (c *PaymentClient) Get(ctx context.Context, id int) (*Payment, error) {
	return c.Query().Where(payment.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *PaymentClient) GetX(ctx context.Context, id int) *Payment {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryLedger queries the ledger edge of a Payment.
func (c *PaymentClient) QueryLedger(_m *Payment) *LedgerQuery {
	query := (&LedgerClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(payment.Table, payment.FieldID, id),
			sqlgraph.To(ledger.Table, ledger.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, payment.LedgerTable, payment.LedgerColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *PaymentClient) Hooks() []Hook {
	return c.hooks.Payment
}

// Interceptors returns the client interceptors.
func (c *PaymentClient) Interceptors() []Interceptor {
	return c.inters.Payment
}

func (c *PaymentClient) mutate(ctx context.Context, m *PaymentMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&PaymentCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&PaymentUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&PaymentUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&PaymentDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown Payment mutation op: %q", m.Op())
	}
}

// SplitClient is a client for the Split schema.
type SplitClient struct {
	config
}

// NewSplitClient returns a client for the Split from the given config.
func NewSplitClient(c config) *SplitClient {
	return &SplitClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `split.Hooks(f(g(h())))`.
func (c *SplitClient) Use(hooks ...Hook) {
	c.hooks.Split = append(c.hooks.Split, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `split.Intercept(f(g(h())))`.
func (c *SplitClient) Intercept(interceptors ...Interceptor) {
	c.inters.Split = append(c.inters.Split, interceptors...)
}

// Create returns a builder for creating a Split entity.
func (c *SplitClient) Create() *SplitCreate {
	mutation := newSplitMutation(c.config, OpCreate)
	return &SplitCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of Split entities.
func (c *SplitClient) CreateBulk(builders ...*SplitCreate) *SplitCreateBulk {
	return &SplitCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *SplitClient) MapCreateBulk(slice any, setFunc func(*SplitCreate, int)) *SplitCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &SplitCreateBulk{err: fmt.Errorf("calling to SplitClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*SplitCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &SplitCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for Split.
func (c *SplitClient) Update() *SplitUpdate {
	mutation := newSplitMutation(c.config, OpUpdate)
	return &SplitUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *SplitClient) UpdateOne(_m *Split) *SplitUpdateOne {
	mutation := newSplitMutation(c.config, OpUpdateOne, withSplit(_m))
	return &SplitUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *SplitClient) UpdateOneID(id int) *SplitUpdateOne {
	mutation := newSplitMutation(c.config, OpUpdateOne, withSplitID(id))
	return &SplitUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for Split.
func (c *SplitClient) Delete() *SplitDelete {
	mutation := newSplitMutation(c.config, OpDelete)
	return &SplitDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *SplitClient) DeleteOne(_m *Split) *SplitDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *SplitClient) DeleteOneID(id int) *SplitDeleteOne {
	builder := c.Delete().Where(split.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &SplitDeleteOne{builder}
}

// Query returns a query builder for Split.
func (c *SplitClient) Query() *SplitQuery {
	return &SplitQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeSplit},
		inters: c.Interceptors(),
	}
}

// Get returns a Split entity by its id.
func (c *SplitClient) Get(ctx context.Context, id int) (*Split, error) {
	return c.Query().Where(split.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *SplitClient) GetX(ctx context.Context, id int) *Split {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryExpense queries the expense edge of a Split.
func (c *SplitClient) QueryExpense(_m *Split) *ExpenseQuery {
	query := (&ExpenseClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(split.Table, split.FieldID, id),
			sqlgraph.To(expense.Table, expense.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, split.ExpenseTable, split.ExpenseColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *SplitClient) Hooks() []Hook {
	return c.hooks.Split
}

// Interceptors returns the client interceptors.
func (c *SplitClient) Interceptors() []Interceptor {
	return c.inters.Split
}

func (c *SplitClient) mutate(ctx context.Context, m *SplitMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&SplitCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&SplitUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&SplitUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&SplitDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown Split mutation op: %q", m.Op())
	}
}

// hooks and interceptors per client, for fast access.
type (
	hooks struct {
		Expense, Ledger, LedgerMember, Payment, Split []ent.Hook
	}
	inters struct {
		Expense, Ledger, LedgerMember, Payment, Split []ent.Interceptor
	}
)
