// Code generated by ent, DO NOT EDIT.

package ent

import (
	"bill-bot/ent/expense"
	"bill-bot/ent/ledger"
	"bill-bot/ent/predicate"
	"bill-bot/ent/split"
	"context"
	"database/sql/driver"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// ExpenseQuery is the builder for querying Expense entities.
type ExpenseQuery struct {
	config
	ctx        *QueryContext
	order      []expense.OrderOption
	inters     []Interceptor
	predicates []predicate.Expense
	withLedger *LedgerQuery
	withSplits *SplitQuery
	withFKs    bool
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the ExpenseQuery builder.
func (_q *ExpenseQuery) Where(ps ...predicate.Expense) *ExpenseQuery {
	_q.predicates = append(_q.predicates, ps...)
	return _q
}

// Limit the number of records to be returned by this query.
func (_q *ExpenseQuery) Limit(limit int) *ExpenseQuery {
	_q.ctx.Limit = &limit
	return _q
}

// Offset to start from.
func (_q *ExpenseQuery) Offset(offset int) *ExpenseQuery {
	_q.ctx.Offset = &offset
	return _q
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (_q *ExpenseQuery) Unique(unique bool) *ExpenseQuery {
	_q.ctx.Unique = &unique
	return _q
}

// Order specifies how the records should be ordered.
func (_q *ExpenseQuery) Order(o ...expense.OrderOption) *ExpenseQuery {
	_q.order = append(_q.order, o...)
	return _q
}

// QueryLedger chains the current query on the "ledger" edge.
func (_q *ExpenseQuery) QueryLedger() *LedgerQuery {
	query := (&LedgerClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(expense.Table, expense.FieldID, selector),
			sqlgraph.To(ledger.Table, ledger.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, expense.LedgerTable, expense.LedgerColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QuerySplits chains the current query on the "splits" edge.
func (_q *ExpenseQuery) QuerySplits() *SplitQuery {
	query := (&SplitClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(expense.Table, expense.FieldID, selector),
			sqlgraph.To(split.Table, split.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, expense.SplitsTable, expense.SplitsColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first Expense entity from the query.
// Returns a *NotFoundError when no Expense was found.
func (_q *ExpenseQuery) First(ctx context.Context) (*Expense, error) {
	nodes, err := _q.Limit(1).All(setContextOp(ctx, _q.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{expense.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (_q *ExpenseQuery) FirstX(ctx context.Context) *Expense {
	node, err := _q.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first Expense ID from the query.
// Returns a *NotFoundError when no Expense ID was found.
func (_q *ExpenseQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = _q.Limit(1).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{expense.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (_q *ExpenseQuery) FirstIDX(ctx context.Context) int {
	id, err := _q.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single Expense entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one Expense entity is found.
// Returns a *NotFoundError when no Expense entities are found.
func (_q *ExpenseQuery) Only(ctx context.Context) (*Expense, error) {
	nodes, err := _q.Limit(2).All(setContextOp(ctx, _q.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{expense.Label}
	default:
		return nil, &NotSingularError{expense.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (_q *ExpenseQuery) OnlyX(ctx context.Context) *Expense {
	node, err := _q.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only Expense ID in the query.
// Returns a *NotSingularError when more than one Expense ID is found.
// Returns a *NotFoundError when no entities are found.
func (_q *ExpenseQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = _q.Limit(2).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{expense.Label}
	default:
		err = &NotSingularError{expense.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (_q *ExpenseQuery) OnlyIDX(ctx context.Context) int {
	id, err := _q.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of Expenses.
func (_q *ExpenseQuery) All(ctx context.Context) ([]*Expense, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryAll)
	if err := _q.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*Expense, *ExpenseQuery]()
	return withInterceptors[[]*Expense](ctx, _q, qr, _q.inters)
}

// AllX is like All, but panics if an error occurs.
func (_q *ExpenseQuery) AllX(ctx context.Context) []*Expense {
	nodes, err := _q.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of Expense IDs.
func (_q *ExpenseQuery) IDs(ctx context.Context) (ids []int, err error) {
	if _q.ctx.Unique == nil && _q.path != nil {
		_q.Unique(true)
	}
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryIDs)
	if err = _q.Select(expense.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (_q *ExpenseQuery) IDsX(ctx context.Context) []int {
	ids, err := _q.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (_q *ExpenseQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryCount)
	if err := _q.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, _q, querierCount[*ExpenseQuery](), _q.inters)
}

// CountX is like Count, but panics if an error occurs.
func (_q *ExpenseQuery) CountX(ctx context.Context) int {
	count, err := _q.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (_q *ExpenseQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryExist)
	switch _, err := _q.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (_q *ExpenseQuery) ExistX(ctx context.Context) bool {
	exist, err := _q.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the ExpenseQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (_q *ExpenseQuery) Clone() *ExpenseQuery {
	if _q == nil {
		return nil
	}
	return &ExpenseQuery{
		config:     _q.config,
		ctx:        _q.ctx.Clone(),
		order:      append([]expense.OrderOption{}, _q.order...),
		inters:     append([]Interceptor{}, _q.inters...),
		predicates: append([]predicate.Expense{}, _q.predicates...),
		withLedger: _q.withLedger.Clone(),
		withSplits: _q.withSplits.Clone(),
		// clone intermediate query.
		sql:  _q.sql.Clone(),
		path: _q.path,
	}
}

// WithLedger tells the query-builder to eager-load the nodes that are connected to
// the "ledger" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *ExpenseQuery) WithLedger(opts ...func(*LedgerQuery)) *ExpenseQuery {
	query := (&LedgerClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withLedger = query
	return _q
}

// WithSplits tells the query-builder to eager-load the nodes that are connected to
// the "splits" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *ExpenseQuery) WithSplits(opts ...func(*SplitQuery)) *ExpenseQuery {
	query := (&SplitClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withSplits = query
	return _q
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		Amount int64 `json:"amount,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.Expense.Query().
//		GroupBy(expense.FieldAmount).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (_q *ExpenseQuery) GroupBy(field string, fields ...string) *ExpenseGroupBy {
	_q.ctx.Fields = append([]string{field}, fields...)
	grbuild := &ExpenseGroupBy{build: _q}
	grbuild.flds = &_q.ctx.Fields
	grbuild.label = expense.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		Amount int64 `json:"amount,omitempty"`
//	}
//
//	client.Expense.Query().
//		Select(expense.FieldAmount).
//		Scan(ctx, &v)
func (_q *ExpenseQuery) Select(fields ...string) *ExpenseSelect {
	_q.ctx.Fields = append(_q.ctx.Fields, fields...)
	sbuild := &ExpenseSelect{ExpenseQuery: _q}
	sbuild.label = expense.Label
	sbuild.flds, sbuild.scan = &_q.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a ExpenseSelect configured with the given aggregations.
func (_q *ExpenseQuery) Aggregate(fns ...AggregateFunc) *ExpenseSelect {
	return _q.Select().Aggregate(fns...)
}

func (_q *ExpenseQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range _q.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, _q); err != nil {
				return err
			}
		}
	}
	for _, f := range _q.ctx.Fields {
		if !expense.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if _q.path != nil {
		prev, err := _q.path(ctx)
		if err != nil {
			return err
		}
		_q.sql = prev
	}
	return nil
}

func (_q *ExpenseQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*Expense, error) {
	var (
		nodes       = []*Expense{}
		withFKs     = _q.withFKs
		_spec       = _q.querySpec()
		loadedTypes = [2]bool{
			_q.withLedger != nil,
			_q.withSplits != nil,
		}
	)
	if _q.withLedger != nil {
		withFKs = true
	}
	if withFKs {
		_spec.Node.Columns = append(_spec.Node.Columns, expense.ForeignKeys...)
	}
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*Expense).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &Expense{config: _q.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, _q.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := _q.withLedger; query != nil {
		if err := _q.loadLedger(ctx, query, nodes, nil,
			func(n *Expense, e *Ledger) { n.Edges.Ledger = e }); err != nil {
			return nil, err
		}
	}
	if query := _q.withSplits; query != nil {
		if err := _q.loadSplits(ctx, query, nodes,
			func(n *Expense) { n.Edges.Splits = []*Split{} },
			func(n *Expense, e *Split) { n.Edges.Splits = append(n.Edges.Splits, e) }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (_q *ExpenseQuery) loadLedger(ctx context.Context, query *LedgerQuery, nodes []*Expense, init func(*Expense), assign func(*Expense, *Ledger)) error {
	ids := make([]int, 0, len(nodes))
	nodeids := make(map[int][]*Expense)
	for i := range nodes {
		if nodes[i].ledger_expenses == nil {
			continue
		}
		fk := *nodes[i].ledger_expenses
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(ledger.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "ledger_expenses" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (_q *ExpenseQuery) loadSplits(ctx context.Context, query *SplitQuery, nodes []*Expense, init func(*Expense), assign func(*Expense, *Split)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[int]*Expense)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	query.withFKs = true
	query.Where(predicate.Split(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(expense.SplitsColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.expense_splits
		if fk == nil {
			return fmt.Errorf(`foreign-key "expense_splits" is nil for node %v`, n.ID)
		}
		node, ok := nodeids[*fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "expense_splits" returned %v for node %v`, *fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}

func (_q *ExpenseQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := _q.querySpec()
	_spec.Node.Columns = _q.ctx.Fields
	if len(_q.ctx.Fields) > 0 {
		_spec.Unique = _q.ctx.Unique != nil && *_q.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, _q.driver, _spec)
}

func (_q *ExpenseQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(expense.Table, expense.Columns, sqlgraph.NewFieldSpec(expense.FieldID, field.TypeInt))
	_spec.From = _q.sql
	if unique := _q.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if _q.path != nil {
		_spec.Unique = true
	}
	if fields := _q.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, expense.FieldID)
		for i := range fields {
			if fields[i] != expense.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := _q.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := _q.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := _q.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := _q.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (_q *ExpenseQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(_q.driver.Dialect())
	t1 := builder.Table(expense.Table)
	columns := _q.ctx.Fields
	if len(columns) == 0 {
		columns = expense.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if _q.sql != nil {
		selector = _q.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if _q.ctx.Unique != nil && *_q.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range _q.predicates {
		p(selector)
	}
	for _, p := range _q.order {
		p(selector)
	}
	if offset := _q.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := _q.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// ExpenseGroupBy is the group-by builder for Expense entities.
type ExpenseGroupBy struct {
	selector
	build *ExpenseQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (_g *ExpenseGroupBy) Aggregate(fns ...AggregateFunc) *ExpenseGroupBy {
	_g.fns = append(_g.fns, fns...)
	return _g
}

// Scan applies the selector query and scans the result into the given value.
func (_g *ExpenseGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _g.build.ctx, ent.OpQueryGroupBy)
	if err := _g.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*ExpenseQuery, *ExpenseGroupBy](ctx, _g.build, _g, _g.build.inters, v)
}

func (_g *ExpenseGroupBy) sqlScan(ctx context.Context, root *ExpenseQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(_g.fns))
	for _, fn := range _g.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*_g.flds)+len(_g.fns))
		for _, f := range *_g.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*_g.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _g.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// ExpenseSelect is the builder for selecting fields of Expense entities.
type ExpenseSelect struct {
	*ExpenseQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (_s *ExpenseSelect) Aggregate(fns ...AggregateFunc) *ExpenseSelect {
	_s.fns = append(_s.fns, fns...)
	return _s
}

// Scan applies the selector query and scans the result into the given value.
func (_s *ExpenseSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _s.ctx, ent.OpQuerySelect)
	if err := _s.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*ExpenseQuery, *ExpenseSelect](ctx, _s.ExpenseQuery, _s, _s.inters, v)
}

func (_s *ExpenseSelect) sqlScan(ctx context.Context, root *ExpenseQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(_s.fns))
	for _, fn := range _s.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*_s.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _s.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
