// Code generated by ent, DO NOT EDIT.

package ent

import (
	"bill-bot/ent/expense"
	"bill-bot/ent/ledger"
	"bill-bot/ent/predicate"
	"bill-bot/ent/split"
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// ExpenseUpdate is the builder for updating Expense entities.
type ExpenseUpdate struct {
	config
	hooks    []Hook
	mutation *ExpenseMutation
}

// Where appends a list predicates to the ExpenseUpdate builder.
func (_u *ExpenseUpdate) Where(ps ...predicate.Expense) *ExpenseUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetAmount sets the "amount" field.
func (_u *ExpenseUpdate) SetAmount(v int64) *ExpenseUpdate {
	_u.mutation.ResetAmount()
	_u.mutation.SetAmount(v)
	return _u
}

// SetNillableAmount sets the "amount" field if the given value is not nil.
func (_u *ExpenseUpdate) SetNillableAmount(v *int64) *ExpenseUpdate {
	if v != nil {
		_u.SetAmount(*v)
	}
	return _u
}

// AddAmount adds value to the "amount" field.
func (_u *ExpenseUpdate) AddAmount(v int64) *ExpenseUpdate {
	_u.mutation.AddAmount(v)
	return _u
}

// SetCurrency sets the "currency" field.
func (_u *ExpenseUpdate) SetCurrency(v string) *ExpenseUpdate {
	_u.mutation.SetCurrency(v)
	return _u
}

// SetNillableCurrency sets the "currency" field if the given value is not nil.
func (_u *ExpenseUpdate) SetNillableCurrency(v *string) *ExpenseUpdate {
	if v != nil {
		_u.SetCurrency(*v)
	}
	return _u
}

// SetDescription sets the "description" field.
func (_u *ExpenseUpdate) SetDescription(v string) *ExpenseUpdate {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *ExpenseUpdate) SetNillableDescription(v *string) *ExpenseUpdate {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// SetPayerID sets the "payer_id" field.
func (_u *ExpenseUpdate) SetPayerID(v string) *ExpenseUpdate {
	_u.mutation.SetPayerID(v)
	return _u
}

// SetNillablePayerID sets the "payer_id" field if the given value is not nil.
func (_u *ExpenseUpdate) SetNillablePayerID(v *string) *ExpenseUpdate {
	if v != nil {
		_u.SetPayerID(*v)
	}
	return _u
}

// SetType sets the "type" field.
func (_u *ExpenseUpdate) SetType(v expense.Type) *ExpenseUpdate {
	_u.mutation.SetType(v)
	return _u
}

// SetNillableType sets the "type" field if the given value is not nil.
func (_u *ExpenseUpdate) SetNillableType(v *expense.Type) *ExpenseUpdate {
	if v != nil {
		_u.SetType(*v)
	}
	return _u
}

// SetDeleted sets the "deleted" field.
func (_u *ExpenseUpdate) SetDeleted(v bool) *ExpenseUpdate {
	_u.mutation.SetDeleted(v)
	return _u
}

// SetNillableDeleted sets the "deleted" field if the given value is not nil.
func (_u *ExpenseUpdate) SetNillableDeleted(v *bool) *ExpenseUpdate {
	if v != nil {
		_u.SetDeleted(*v)
	}
	return _u
}

// SetLedgerID sets the "ledger" edge to the Ledger entity by ID.
func (_u *ExpenseUpdate) SetLedgerID(id int) *ExpenseUpdate {
	_u.mutation.SetLedgerID(id)
	return _u
}

// SetLedger sets the "ledger" edge to the Ledger entity.
func (_u *ExpenseUpdate) SetLedger(v *Ledger) *ExpenseUpdate {
	return _u.SetLedgerID(v.ID)
}

// AddSplitIDs adds the "splits" edge to the Split entity by IDs.
func (_u *ExpenseUpdate) AddSplitIDs(ids ...int) *ExpenseUpdate {
	_u.mutation.AddSplitIDs(ids...)
	return _u
}

// AddSplits adds the "splits" edges to the Split entity.
func (_u *ExpenseUpdate) AddSplits(v ...*Split) *ExpenseUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddSplitIDs(ids...)
}

// Mutation returns the ExpenseMutation object of the builder.
func (_u *ExpenseUpdate) Mutation() *ExpenseMutation {
	return _u.mutation
}

// ClearLedger clears the "ledger" edge to the Ledger entity.
func (_u *ExpenseUpdate) ClearLedger() *ExpenseUpdate {
	_u.mutation.ClearLedger()
	return _u
}

// ClearSplits clears all "splits" edges to the Split entity.
func (_u *ExpenseUpdate) ClearSplits() *ExpenseUpdate {
	_u.mutation.ClearSplits()
	return _u
}

// RemoveSplitIDs removes the "splits" edge to Split entities by IDs.
func (_u *ExpenseUpdate) RemoveSplitIDs(ids ...int) *ExpenseUpdate {
	_u.mutation.RemoveSplitIDs(ids...)
	return _u
}

// RemoveSplits removes "splits" edges to Split entities.
func (_u *ExpenseUpdate) RemoveSplits(v ...*Split) *ExpenseUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveSplitIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *ExpenseUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ExpenseUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *ExpenseUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ExpenseUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ExpenseUpdate) check() error {
	if v, ok := _u.mutation.GetType(); ok {
		if err := expense.TypeValidator(v); err != nil {
			return &ValidationError{Name: "type", err: fmt.Errorf(`ent: validator failed for field "Expense.type": %w`, err)}
		}
	}
	if _u.mutation.LedgerCleared() && len(_u.mutation.LedgerIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Expense.ledger"`)
	}
	return nil
}

func (_u *ExpenseUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(expense.Table, expense.Columns, sqlgraph.NewFieldSpec(expense.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Amount(); ok {
		_spec.SetField(expense.FieldAmount, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedAmount(); ok {
		_spec.AddField(expense.FieldAmount, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.Currency(); ok {
		_spec.SetField(expense.FieldCurrency, field.TypeString, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(expense.FieldDescription, field.TypeString, value)
	}
	if value, ok := _u.mutation.PayerID(); ok {
		_spec.SetField(expense.FieldPayerID, field.TypeString, value)
	}
	if value, ok := _u.mutation.GetType(); ok {
		_spec.SetField(expense.FieldType, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Deleted(); ok {
		_spec.SetField(expense.FieldDeleted, field.TypeBool, value)
	}
	if _u.mutation.LedgerCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   expense.LedgerTable,
			Columns: []string{expense.LedgerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(ledger.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.LedgerIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   expense.LedgerTable,
			Columns: []string{expense.LedgerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(ledger.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.SplitsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   expense.SplitsTable,
			Columns: []string{expense.SplitsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(split.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedSplitsIDs(); len(nodes) > 0 && !_u.mutation.SplitsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   expense.SplitsTable,
			Columns: []string{expense.SplitsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(split.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.SplitsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   expense.SplitsTable,
			Columns: []string{expense.SplitsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(split.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{expense.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// ExpenseUpdateOne is the builder for updating a single Expense entity.
type ExpenseUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ExpenseMutation
}

// SetAmount sets the "amount" field.
func (_u *ExpenseUpdateOne) SetAmount(v int64) *ExpenseUpdateOne {
	_u.mutation.ResetAmount()
	_u.mutation.SetAmount(v)
	return _u
}

// SetNillableAmount sets the "amount" field if the given value is not nil.
func (_u *ExpenseUpdateOne) SetNillableAmount(v *int64) *ExpenseUpdateOne {
	if v != nil {
		_u.SetAmount(*v)
	}
	return _u
}

// AddAmount adds value to the "amount" field.
func (_u *ExpenseUpdateOne) AddAmount(v int64) *ExpenseUpdateOne {
	_u.mutation.AddAmount(v)
	return _u
}

// SetCurrency sets the "currency" field.
func (_u *ExpenseUpdateOne) SetCurrency(v string) *ExpenseUpdateOne {
	_u.mutation.SetCurrency(v)
	return _u
}

// SetNillableCurrency sets the "currency" field if the given value is not nil.
func (_u *ExpenseUpdateOne) SetNillableCurrency(v *string) *ExpenseUpdateOne {
	if v != nil {
		_u.SetCurrency(*v)
	}
	return _u
}

// SetDescription sets the "description" field.
func (_u *ExpenseUpdateOne) SetDescription(v string) *ExpenseUpdateOne {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *ExpenseUpdateOne) SetNillableDescription(v *string) *ExpenseUpdateOne {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// SetPayerID sets the "payer_id" field.
func (_u *ExpenseUpdateOne) SetPayerID(v string) *ExpenseUpdateOne {
	_u.mutation.SetPayerID(v)
	return _u
}

// SetNillablePayerID sets the "payer_id" field if the given value is not nil.
func (_u *ExpenseUpdateOne) SetNillablePayerID(v *string) *ExpenseUpdateOne {
	if v != nil {
		_u.SetPayerID(*v)
	}
	return _u
}

// SetType sets the "type" field.
func (_u *ExpenseUpdateOne) SetType(v expense.Type) *ExpenseUpdateOne {
	_u.mutation.SetType(v)
	return _u
}

// SetNillableType sets the "type" field if the given value is not nil.
func (_u *ExpenseUpdateOne) SetNillableType(v *expense.Type) *ExpenseUpdateOne {
	if v != nil {
		_u.SetType(*v)
	}
	return _u
}

// SetDeleted sets the "deleted" field.
func (_u *ExpenseUpdateOne) SetDeleted(v bool) *ExpenseUpdateOne {
	_u.mutation.SetDeleted(v)
	return _u
}

// SetNillableDeleted sets the "deleted" field if the given value is not nil.
func (_u *ExpenseUpdateOne) SetNillableDeleted(v *bool) *ExpenseUpdateOne {
	if v != nil {
		_u.SetDeleted(*v)
	}
	return _u
}

// SetLedgerID sets the "ledger" edge to the Ledger entity by ID.
func (_u *ExpenseUpdateOne) SetLedgerID(id int) *ExpenseUpdateOne {
	_u.mutation.SetLedgerID(id)
	return _u
}

// SetLedger sets the "ledger" edge to the Ledger entity.
func (_u *ExpenseUpdateOne) SetLedger(v *Ledger) *ExpenseUpdateOne {
	return _u.SetLedgerID(v.ID)
}

// AddSplitIDs adds the "splits" edge to the Split entity by IDs.
func (_u *ExpenseUpdateOne) AddSplitIDs(ids ...int) *ExpenseUpdateOne {
	_u.mutation.AddSplitIDs(ids...)
	return _u
}

// AddSplits adds the "splits" edges to the Split entity.
func (_u *ExpenseUpdateOne) AddSplits(v ...*Split) *ExpenseUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddSplitIDs(ids...)
}

// Mutation returns the ExpenseMutation object of the builder.
func (_u *ExpenseUpdateOne) Mutation() *ExpenseMutation {
	return _u.mutation
}

// ClearLedger clears the "ledger" edge to the Ledger entity.
func (_u *ExpenseUpdateOne) ClearLedger() *ExpenseUpdateOne {
	_u.mutation.ClearLedger()
	return _u
}

// ClearSplits clears all "splits" edges to the Split entity.
func (_u *ExpenseUpdateOne) ClearSplits() *ExpenseUpdateOne {
	_u.mutation.ClearSplits()
	return _u
}

// RemoveSplitIDs removes the "splits" edge to Split entities by IDs.
func (_u *ExpenseUpdateOne) RemoveSplitIDs(ids ...int) *ExpenseUpdateOne {
	_u.mutation.RemoveSplitIDs(ids...)
	return _u
}

// RemoveSplits removes "splits" edges to Split entities.
func (_u *ExpenseUpdateOne) RemoveSplits(v ...*Split) *ExpenseUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveSplitIDs(ids...)
}

// Where appends a list predicates to the ExpenseUpdate builder.
func (_u *ExpenseUpdateOne) Where(ps ...predicate.Expense) *ExpenseUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *ExpenseUpdateOne) Select(field string, fields ...string) *ExpenseUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Expense entity.
func (_u *ExpenseUpdateOne) Save(ctx context.Context) (*Expense, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ExpenseUpdateOne) SaveX(ctx context.Context) *Expense {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *ExpenseUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ExpenseUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ExpenseUpdateOne) check() error {
	if v, ok := _u.mutation.GetType(); ok {
		if err := expense.TypeValidator(v); err != nil {
			return &ValidationError{Name: "type", err: fmt.Errorf(`ent: validator failed for field "Expense.type": %w`, err)}
		}
	}
	if _u.mutation.LedgerCleared() && len(_u.mutation.LedgerIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Expense.ledger"`)
	}
	return nil
}

func (_u *ExpenseUpdateOne) sqlSave(ctx context.Context) (_node *Expense, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(expense.Table, expense.Columns, sqlgraph.NewFieldSpec(expense.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Expense.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, expense.FieldID)
		for _, f := range fields {
			if !expense.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != expense.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Amount(); ok {
		_spec.SetField(expense.FieldAmount, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedAmount(); ok {
		_spec.AddField(expense.FieldAmount, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.Currency(); ok {
		_spec.SetField(expense.FieldCurrency, field.TypeString, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(expense.FieldDescription, field.TypeString, value)
	}
	if value, ok := _u.mutation.PayerID(); ok {
		_spec.SetField(expense.FieldPayerID, field.TypeString, value)
	}
	if value, ok := _u.mutation.GetType(); ok {
		_spec.SetField(expense.FieldType, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Deleted(); ok {
		_spec.SetField(expense.FieldDeleted, field.TypeBool, value)
	}
	if _u.mutation.LedgerCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   expense.LedgerTable,
			Columns: []string{expense.LedgerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(ledger.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.LedgerIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   expense.LedgerTable,
			Columns: []string{expense.LedgerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(ledger.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.SplitsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   expense.SplitsTable,
			Columns: []string{expense.SplitsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(split.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedSplitsIDs(); len(nodes) > 0 && !_u.mutation.SplitsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   expense.SplitsTable,
			Columns: []string{expense.SplitsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(split.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.SplitsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   expense.SplitsTable,
			Columns: []string{expense.SplitsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(split.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Expense{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{expense.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
