// Code generated by ent, DO NOT EDIT.

package ent

import (
	"bill-bot/ent/expense"
	"bill-bot/ent/ledger"
	"bill-bot/ent/split"
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// ExpenseCreate is the builder for creating a Expense entity.
type ExpenseCreate struct {
	config
	mutation *ExpenseMutation
	hooks    []Hook
}

// SetAmount sets the "amount" field.
func (_c *ExpenseCreate) SetAmount(v int64) *ExpenseCreate {
	_c.mutation.SetAmount(v)
	return _c
}

// SetCurrency sets the "currency" field.
func (_c *ExpenseCreate) SetCurrency(v string) *ExpenseCreate {
	_c.mutation.SetCurrency(v)
	return _c
}

// SetNillableCurrency sets the "currency" field if the given value is not nil.
func (_c *ExpenseCreate) SetNillableCurrency(v *string) *ExpenseCreate {
	if v != nil {
		_c.SetCurrency(*v)
	}
	return _c
}

// SetDescription sets the "description" field.
func (_c *ExpenseCreate) SetDescription(v string) *ExpenseCreate {
	_c.mutation.SetDescription(v)
	return _c
}

// SetPayerID sets the "payer_id" field.
func (_c *ExpenseCreate) SetPayerID(v string) *ExpenseCreate {
	_c.mutation.SetPayerID(v)
	return _c
}

// SetType sets the "type" field.
func (_c *ExpenseCreate) SetType(v expense.Type) *ExpenseCreate {
	_c.mutation.SetType(v)
	return _c
}

// SetDeleted sets the "deleted" field.
func (_c *ExpenseCreate) SetDeleted(v bool) *ExpenseCreate {
	_c.mutation.SetDeleted(v)
	return _c
}

// SetNillableDeleted sets the "deleted" field if the given value is not nil.
func (_c *ExpenseCreate) SetNillableDeleted(v *bool) *ExpenseCreate {
	if v != nil {
		_c.SetDeleted(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *ExpenseCreate) SetCreatedAt(v time.Time) *ExpenseCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *ExpenseCreate) SetNillableCreatedAt(v *time.Time) *ExpenseCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetLedgerID sets the "ledger" edge to the Ledger entity by ID.
func (_c *ExpenseCreate) SetLedgerID(id int) *ExpenseCreate {
	_c.mutation.SetLedgerID(id)
	return _c
}

// SetLedger sets the "ledger" edge to the Ledger entity.
func (_c *ExpenseCreate) SetLedger(v *Ledger) *ExpenseCreate {
	return _c.SetLedgerID(v.ID)
}

// AddSplitIDs adds the "splits" edge to the Split entity by IDs.
func (_c *ExpenseCreate) AddSplitIDs(ids ...int) *ExpenseCreate {
	_c.mutation.AddSplitIDs(ids...)
	return _c
}

// AddSplits adds the "splits" edges to the Split entity.
func (_c *ExpenseCreate) AddSplits(v ...*Split) *ExpenseCreate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddSplitIDs(ids...)
}

// Mutation returns the ExpenseMutation object of the builder.
func (_c *ExpenseCreate) Mutation() *ExpenseMutation {
	return _c.mutation
}

// Save creates the Expense in the database.
func (_c *ExpenseCreate) Save(ctx context.Context) (*Expense, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *ExpenseCreate) SaveX(ctx context.Context) *Expense {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ExpenseCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ExpenseCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *ExpenseCreate) defaults() {
	if _, ok := _c.mutation.Currency(); !ok {
		v := expense.DefaultCurrency
		_c.mutation.SetCurrency(v)
	}
	if _, ok := _c.mutation.Deleted(); !ok {
		v := expense.DefaultDeleted
		_c.mutation.SetDeleted(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := expense.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *ExpenseCreate) check() error {
	if _, ok := _c.mutation.Amount(); !ok {
		return &ValidationError{Name: "amount", err: errors.New(`ent: missing required field "Expense.amount"`)}
	}
	if _, ok := _c.mutation.Currency(); !ok {
		return &ValidationError{Name: "currency", err: errors.New(`ent: missing required field "Expense.currency"`)}
	}
	if _, ok := _c.mutation.Description(); !ok {
		return &ValidationError{Name: "description", err: errors.New(`ent: missing required field "Expense.description"`)}
	}
	if _, ok := _c.mutation.PayerID(); !ok {
		return &ValidationError{Name: "payer_id", err: errors.New(`ent: missing required field "Expense.payer_id"`)}
	}
	if _, ok := _c.mutation.GetType(); !ok {
		return &ValidationError{Name: "type", err: errors.New(`ent: missing required field "Expense.type"`)}
	}
	if v, ok := _c.mutation.GetType(); ok {
		if err := expense.TypeValidator(v); err != nil {
			return &ValidationError{Name: "type", err: fmt.Errorf(`ent: validator failed for field "Expense.type": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Deleted(); !ok {
		return &ValidationError{Name: "deleted", err: errors.New(`ent: missing required field "Expense.deleted"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Expense.created_at"`)}
	}
	if len(_c.mutation.LedgerIDs()) == 0 {
		return &ValidationError{Name: "ledger", err: errors.New(`ent: missing required edge "Expense.ledger"`)}
	}
	return nil
}

func (_c *ExpenseCreate) sqlSave(ctx context.Context) (*Expense, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *ExpenseCreate) createSpec() (*Expense, *sqlgraph.CreateSpec) {
	var (
		_node = &Expense{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(expense.Table, sqlgraph.NewFieldSpec(expense.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.Amount(); ok {
		_spec.SetField(expense.FieldAmount, field.TypeInt64, value)
		_node.Amount = value
	}
	if value, ok := _c.mutation.Currency(); ok {
		_spec.SetField(expense.FieldCurrency, field.TypeString, value)
		_node.Currency = value
	}
	if value, ok := _c.mutation.Description(); ok {
		_spec.SetField(expense.FieldDescription, field.TypeString, value)
		_node.Description = value
	}
	if value, ok := _c.mutation.PayerID(); ok {
		_spec.SetField(expense.FieldPayerID, field.TypeString, value)
		_node.PayerID = value
	}
	if value, ok := _c.mutation.GetType(); ok {
		_spec.SetField(expense.FieldType, field.TypeEnum, value)
		_node.Type = value
	}
	if value, ok := _c.mutation.Deleted(); ok {
		_spec.SetField(expense.FieldDeleted, field.TypeBool, value)
		_node.Deleted = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(expense.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if nodes := _c.mutation.LedgerIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   expense.LedgerTable,
			Columns: []string{expense.LedgerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(ledger.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.ledger_expenses = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.SplitsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   expense.SplitsTable,
			Columns: []string{expense.SplitsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(split.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// ExpenseCreateBulk is the builder for creating many Expense entities in bulk.
type ExpenseCreateBulk struct {
	config
	err      error
	builders []*ExpenseCreate
}

// Save creates the Expense entities in the database.
func (_c *ExpenseCreateBulk) Save(ctx context.Context) ([]*Expense, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Expense, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ExpenseMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *ExpenseCreateBulk) SaveX(ctx context.Context) []*Expense {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ExpenseCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ExpenseCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
