// Code generated by ent, DO NOT EDIT.

package ent

import (
	"bill-bot/ent/expense"
	"bill-bot/ent/ledger"
	"bill-bot/ent/ledgermember"
	"bill-bot/ent/payment"
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// LedgerCreate is the builder for creating a Ledger entity.
type LedgerCreate struct {
	config
	mutation *LedgerMutation
	hooks    []Hook
}

// SetChannelID sets the "channel_id" field.
func (_c *LedgerCreate) SetChannelID(v string) *LedgerCreate {
	_c.mutation.SetChannelID(v)
	return _c
}

// SetGuildID sets the "guild_id" field.
func (_c *LedgerCreate) SetGuildID(v string) *LedgerCreate {
	_c.mutation.SetGuildID(v)
	return _c
}

// SetCategoryID sets the "category_id" field.
func (_c *LedgerCreate) SetCategoryID(v string) *LedgerCreate {
	_c.mutation.SetCategoryID(v)
	return _c
}

// SetNillableCategoryID sets the "category_id" field if the given value is not nil.
func (_c *LedgerCreate) SetNillableCategoryID(v *string) *LedgerCreate {
	if v != nil {
		_c.SetCategoryID(*v)
	}
	return _c
}

// SetPinnedMessageID sets the "pinned_message_id" field.
func (_c *LedgerCreate) SetPinnedMessageID(v string) *LedgerCreate {
	_c.mutation.SetPinnedMessageID(v)
	return _c
}

// SetNillablePinnedMessageID sets the "pinned_message_id" field if the given value is not nil.
func (_c *LedgerCreate) SetNillablePinnedMessageID(v *string) *LedgerCreate {
	if v != nil {
		_c.SetPinnedMessageID(*v)
	}
	return _c
}

// SetActive sets the "active" field.
func (_c *LedgerCreate) SetActive(v bool) *LedgerCreate {
	_c.mutation.SetActive(v)
	return _c
}

// SetNillableActive sets the "active" field if the given value is not nil.
func (_c *LedgerCreate) SetNillableActive(v *bool) *LedgerCreate {
	if v != nil {
		_c.SetActive(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *LedgerCreate) SetCreatedAt(v time.Time) *LedgerCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *LedgerCreate) SetNillableCreatedAt(v *time.Time) *LedgerCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// AddExpenseIDs adds the "expenses" edge to the Expense entity by IDs.
func (_c *LedgerCreate) AddExpenseIDs(ids ...int) *LedgerCreate {
	_c.mutation.AddExpenseIDs(ids...)
	return _c
}

// AddExpenses adds the "expenses" edges to the Expense entity.
func (_c *LedgerCreate) AddExpenses(v ...*Expense) *LedgerCreate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddExpenseIDs(ids...)
}

// AddPaymentIDs adds the "payments" edge to the Payment entity by IDs.
func (_c *LedgerCreate) AddPaymentIDs(ids ...int) *LedgerCreate {
	_c.mutation.AddPaymentIDs(ids...)
	return _c
}

// AddPayments adds the "payments" edges to the Payment entity.
func (_c *LedgerCreate) AddPayments(v ...*Payment) *LedgerCreate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddPaymentIDs(ids...)
}

// AddMemberIDs adds the "members" edge to the LedgerMember entity by IDs.
func (_c *LedgerCreate) AddMemberIDs(ids ...int) *LedgerCreate {
	_c.mutation.AddMemberIDs(ids...)
	return _c
}

// AddMembers adds the "members" edges to the LedgerMember entity.
func (_c *LedgerCreate) AddMembers(v ...*LedgerMember) *LedgerCreate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddMemberIDs(ids...)
}

// Mutation returns the LedgerMutation object of the builder.
func (_c *LedgerCreate) Mutation() *LedgerMutation {
	return _c.mutation
}

// Save creates the Ledger in the database.
func (_c *LedgerCreate) Save(ctx context.Context) (*Ledger, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *LedgerCreate) SaveX(ctx context.Context) *Ledger {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *LedgerCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *LedgerCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *LedgerCreate) defaults() {
	if _, ok := _c.mutation.Active(); !ok {
		v := ledger.DefaultActive
		_c.mutation.SetActive(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := ledger.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *LedgerCreate) check() error {
	if _, ok := _c.mutation.ChannelID(); !ok {
		return &ValidationError{Name: "channel_id", err: errors.New(`ent: missing required field "Ledger.channel_id"`)}
	}
	if _, ok := _c.mutation.GuildID(); !ok {
		return &ValidationError{Name: "guild_id", err: errors.New(`ent: missing required field "Ledger.guild_id"`)}
	}
	if _, ok := _c.mutation.Active(); !ok {
		return &ValidationError{Name: "active", err: errors.New(`ent: missing required field "Ledger.active"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Ledger.created_at"`)}
	}
	return nil
}

func (_c *LedgerCreate) sqlSave(ctx context.Context) (*Ledger, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *LedgerCreate) createSpec() (*Ledger, *sqlgraph.CreateSpec) {
	var (
		_node = &Ledger{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(ledger.Table, sqlgraph.NewFieldSpec(ledger.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.ChannelID(); ok {
		_spec.SetField(ledger.FieldChannelID, field.TypeString, value)
		_node.ChannelID = value
	}
	if value, ok := _c.mutation.GuildID(); ok {
		_spec.SetField(ledger.FieldGuildID, field.TypeString, value)
		_node.GuildID = value
	}
	if value, ok := _c.mutation.CategoryID(); ok {
		_spec.SetField(ledger.FieldCategoryID, field.TypeString, value)
		_node.CategoryID = value
	}
	if value, ok := _c.mutation.PinnedMessageID(); ok {
		_spec.SetField(ledger.FieldPinnedMessageID, field.TypeString, value)
		_node.PinnedMessageID = value
	}
	if value, ok := _c.mutation.Active(); ok {
		_spec.SetField(ledger.FieldActive, field.TypeBool, value)
		_node.Active = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(ledger.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if nodes := _c.mutation.ExpensesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   ledger.ExpensesTable,
			Columns: []string{ledger.ExpensesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(expense.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.PaymentsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   ledger.PaymentsTable,
			Columns: []string{ledger.PaymentsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(payment.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.MembersIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   ledger.MembersTable,
			Columns: []string{ledger.MembersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(ledgermember.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// LedgerCreateBulk is the builder for creating many Ledger entities in bulk.
type LedgerCreateBulk struct {
	config
	err      error
	builders []*LedgerCreate
}

// Save creates the Ledger entities in the database.
func (_c *LedgerCreateBulk) Save(ctx context.Context) ([]*Ledger, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Ledger, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*LedgerMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *LedgerCreateBulk) SaveX(ctx context.Context) []*Ledger {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *LedgerCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *LedgerCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
