// Code generated by ent, DO NOT EDIT.

package ent

import (
	"bill-bot/ent/ledger"
	"bill-bot/ent/ledgermember"
	"bill-bot/ent/predicate"
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// LedgerMemberUpdate is the builder for updating LedgerMember entities.
type LedgerMemberUpdate struct {
	config
	hooks    []Hook
	mutation *LedgerMemberMutation
}

// Where appends a list predicates to the LedgerMemberUpdate builder.
func (_u *LedgerMemberUpdate) Where(ps ...predicate.LedgerMember) *LedgerMemberUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *LedgerMemberUpdate) SetUserID(v string) *LedgerMemberUpdate {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *LedgerMemberUpdate) SetNillableUserID(v *string) *LedgerMemberUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetUserName sets the "user_name" field.
func (_u *LedgerMemberUpdate) SetUserName(v string) *LedgerMemberUpdate {
	_u.mutation.SetUserName(v)
	return _u
}

// SetNillableUserName sets the "user_name" field if the given value is not nil.
func (_u *LedgerMemberUpdate) SetNillableUserName(v *string) *LedgerMemberUpdate {
	if v != nil {
		_u.SetUserName(*v)
	}
	return _u
}

// SetActive sets the "active" field.
func (_u *LedgerMemberUpdate) SetActive(v bool) *LedgerMemberUpdate {
	_u.mutation.SetActive(v)
	return _u
}

// SetNillableActive sets the "active" field if the given value is not nil.
func (_u *LedgerMemberUpdate) SetNillableActive(v *bool) *LedgerMemberUpdate {
	if v != nil {
		_u.SetActive(*v)
	}
	return _u
}

// SetLedgerID sets the "ledger" edge to the Ledger entity by ID.
func (_u *LedgerMemberUpdate) SetLedgerID(id int) *LedgerMemberUpdate {
	_u.mutation.SetLedgerID(id)
	return _u
}

// SetLedger sets the "ledger" edge to the Ledger entity.
func (_u *LedgerMemberUpdate) SetLedger(v *Ledger) *LedgerMemberUpdate {
	return _u.SetLedgerID(v.ID)
}

// Mutation returns the LedgerMemberMutation object of the builder.
func (_u *LedgerMemberUpdate) Mutation() *LedgerMemberMutation {
	return _u.mutation
}

// ClearLedger clears the "ledger" edge to the Ledger entity.
func (_u *LedgerMemberUpdate) ClearLedger() *LedgerMemberUpdate {
	_u.mutation.ClearLedger()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *LedgerMemberUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *LedgerMemberUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *LedgerMemberUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *LedgerMemberUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *LedgerMemberUpdate) check() error {
	if _u.mutation.LedgerCleared() && len(_u.mutation.LedgerIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "LedgerMember.ledger"`)
	}
	return nil
}

func (_u *LedgerMemberUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(ledgermember.Table, ledgermember.Columns, sqlgraph.NewFieldSpec(ledgermember.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UserID(); ok {
		_spec.SetField(ledgermember.FieldUserID, field.TypeString, value)
	}
	if value, ok := _u.mutation.UserName(); ok {
		_spec.SetField(ledgermember.FieldUserName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Active(); ok {
		_spec.SetField(ledgermember.FieldActive, field.TypeBool, value)
	}
	if _u.mutation.LedgerCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   ledgermember.LedgerTable,
			Columns: []string{ledgermember.LedgerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(ledger.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.LedgerIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   ledgermember.LedgerTable,
			Columns: []string{ledgermember.LedgerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(ledger.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{ledgermember.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// LedgerMemberUpdateOne is the builder for updating a single LedgerMember entity.
type LedgerMemberUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *LedgerMemberMutation
}

// SetUserID sets the "user_id" field.
func (_u *LedgerMemberUpdateOne) SetUserID(v string) *LedgerMemberUpdateOne {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *LedgerMemberUpdateOne) SetNillableUserID(v *string) *LedgerMemberUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetUserName sets the "user_name" field.
func (_u *LedgerMemberUpdateOne) SetUserName(v string) *LedgerMemberUpdateOne {
	_u.mutation.SetUserName(v)
	return _u
}

// SetNillableUserName sets the "user_name" field if the given value is not nil.
func (_u *LedgerMemberUpdateOne) SetNillableUserName(v *string) *LedgerMemberUpdateOne {
	if v != nil {
		_u.SetUserName(*v)
	}
	return _u
}

// SetActive sets the "active" field.
func (_u *LedgerMemberUpdateOne) SetActive(v bool) *LedgerMemberUpdateOne {
	_u.mutation.SetActive(v)
	return _u
}

// SetNillableActive sets the "active" field if the given value is not nil.
func (_u *LedgerMemberUpdateOne) SetNillableActive(v *bool) *LedgerMemberUpdateOne {
	if v != nil {
		_u.SetActive(*v)
	}
	return _u
}

// SetLedgerID sets the "ledger" edge to the Ledger entity by ID.
func (_u *LedgerMemberUpdateOne) SetLedgerID(id int) *LedgerMemberUpdateOne {
	_u.mutation.SetLedgerID(id)
	return _u
}

// SetLedger sets the "ledger" edge to the Ledger entity.
func (_u *LedgerMemberUpdateOne) SetLedger(v *Ledger) *LedgerMemberUpdateOne {
	return _u.SetLedgerID(v.ID)
}

// Mutation returns the LedgerMemberMutation object of the builder.
func (_u *LedgerMemberUpdateOne) Mutation() *LedgerMemberMutation {
	return _u.mutation
}

// ClearLedger clears the "ledger" edge to the Ledger entity.
func (_u *LedgerMemberUpdateOne) ClearLedger() *LedgerMemberUpdateOne {
	_u.mutation.ClearLedger()
	return _u
}

// Where appends a list predicates to the LedgerMemberUpdate builder.
func (_u *LedgerMemberUpdateOne) Where(ps ...predicate.LedgerMember) *LedgerMemberUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *LedgerMemberUpdateOne) Select(field string, fields ...string) *LedgerMemberUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated LedgerMember entity.
func (_u *LedgerMemberUpdateOne) Save(ctx context.Context) (*LedgerMember, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *LedgerMemberUpdateOne) SaveX(ctx context.Context) *LedgerMember {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *LedgerMemberUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *LedgerMemberUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *LedgerMemberUpdateOne) check() error {
	if _u.mutation.LedgerCleared() && len(_u.mutation.LedgerIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "LedgerMember.ledger"`)
	}
	return nil
}

func (_u *LedgerMemberUpdateOne) sqlSave(ctx context.Context) (_node *LedgerMember, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(ledgermember.Table, ledgermember.Columns, sqlgraph.NewFieldSpec(ledgermember.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "LedgerMember.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, ledgermember.FieldID)
		for _, f := range fields {
			if !ledgermember.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != ledgermember.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UserID(); ok {
		_spec.SetField(ledgermember.FieldUserID, field.TypeString, value)
	}
	if value, ok := _u.mutation.UserName(); ok {
		_spec.SetField(ledgermember.FieldUserName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Active(); ok {
		_spec.SetField(ledgermember.FieldActive, field.TypeBool, value)
	}
	if _u.mutation.LedgerCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   ledgermember.LedgerTable,
			Columns: []string{ledgermember.LedgerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(ledger.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.LedgerIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   ledgermember.LedgerTable,
			Columns: []string{ledgermember.LedgerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(ledger.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &LedgerMember{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{ledgermember.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
