// Code generated by ent, DO NOT EDIT.

package ent

import (
	"bill-bot/ent/ledgermember"
	"bill-bot/ent/predicate"
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// LedgerMemberDelete is the builder for deleting a LedgerMember entity.
type LedgerMemberDelete struct {
	config
	hooks    []Hook
	mutation *LedgerMemberMutation
}

// Where appends a list predicates to the LedgerMemberDelete builder.
func (_d *LedgerMemberDelete) Where(ps ...predicate.LedgerMember) *LedgerMemberDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *LedgerMemberDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *LedgerMemberDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *LedgerMemberDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(ledgermember.Table, sqlgraph.NewFieldSpec(ledgermember.FieldID, field.TypeInt))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// LedgerMemberDeleteOne is the builder for deleting a single LedgerMember entity.
type LedgerMemberDeleteOne struct {
	_d *LedgerMemberDelete
}

// Where appends a list predicates to the LedgerMemberDelete builder.
func (_d *LedgerMemberDeleteOne) Where(ps ...predicate.LedgerMember) *LedgerMemberDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *LedgerMemberDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{ledgermember.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *LedgerMemberDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
