// Code generated by ent, DO NOT EDIT.

package ent

import (
	"bill-bot/ent/ledger"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// Ledger is the model entity for the Ledger schema.
type Ledger struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// ChannelID holds the value of the "channel_id" field.
	ChannelID string `json:"channel_id,omitempty"`
	// GuildID holds the value of the "guild_id" field.
	GuildID string `json:"guild_id,omitempty"`
	// CategoryID holds the value of the "category_id" field.
	CategoryID string `json:"category_id,omitempty"`
	// PinnedMessageID holds the value of the "pinned_message_id" field.
	PinnedMessageID string `json:"pinned_message_id,omitempty"`
	// Active holds the value of the "active" field.
	Active bool `json:"active,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the LedgerQuery when eager-loading is set.
	Edges        LedgerEdges `json:"edges"`
	selectValues sql.SelectValues
}

// LedgerEdges holds the relations/edges for other nodes in the graph.
type LedgerEdges struct {
	// Expenses holds the value of the expenses edge.
	Expenses []*Expense `json:"expenses,omitempty"`
	// Payments holds the value of the payments edge.
	Payments []*Payment `json:"payments,omitempty"`
	// Members holds the value of the members edge.
	Members []*LedgerMember `json:"members,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [3]bool
}

// ExpensesOrErr returns the Expenses value or an error if the edge
// was not loaded in eager-loading.
func (e LedgerEdges) ExpensesOrErr() ([]*Expense, error) {
	if e.loadedTypes[0] {
		return e.Expenses, nil
	}
	return nil, &NotLoadedError{edge: "expenses"}
}

// PaymentsOrErr returns the Payments value or an error if the edge
// was not loaded in eager-loading.
func (e LedgerEdges) PaymentsOrErr() ([]*Payment, error) {
	if e.loadedTypes[1] {
		return e.Payments, nil
	}
	return nil, &NotLoadedError{edge: "payments"}
}

// MembersOrErr returns the Members value or an error if the edge
// was not loaded in eager-loading.
func (e LedgerEdges) MembersOrErr() ([]*LedgerMember, error) {
	if e.loadedTypes[2] {
		return e.Members, nil
	}
	return nil, &NotLoadedError{edge: "members"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Ledger) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case ledger.FieldActive:
			values[i] = new(sql.NullBool)
		case ledger.FieldID:
			values[i] = new(sql.NullInt64)
		case ledger.FieldChannelID, ledger.FieldGuildID, ledger.FieldCategoryID, ledger.FieldPinnedMessageID:
			values[i] = new(sql.NullString)
		case ledger.FieldCreatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Ledger fields.
func (_m *Ledger) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case ledger.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case ledger.FieldChannelID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field channel_id", values[i])
			} else if value.Valid {
				_m.ChannelID = value.String
			}
		case ledger.FieldGuildID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field guild_id", values[i])
			} else if value.Valid {
				_m.GuildID = value.String
			}
		case ledger.FieldCategoryID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field category_id", values[i])
			} else if value.Valid {
				_m.CategoryID = value.String
			}
		case ledger.FieldPinnedMessageID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field pinned_message_id", values[i])
			} else if value.Valid {
				_m.PinnedMessageID = value.String
			}
		case ledger.FieldActive:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field active", values[i])
			} else if value.Valid {
				_m.Active = value.Bool
			}
		case ledger.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Ledger.
// This includes values selected through modifiers, order, etc.
func (_m *Ledger) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryExpenses queries the "expenses" edge of the Ledger entity.
func (_m *Ledger) QueryExpenses() *ExpenseQuery {
	return NewLedgerClient(_m.config).QueryExpenses(_m)
}

// QueryPayments queries the "payments" edge of the Ledger entity.
func (_m *Ledger) QueryPayments() *PaymentQuery {
	return NewLedgerClient(_m.config).QueryPayments(_m)
}

// QueryMembers queries the "members" edge of the Ledger entity.
func (_m *Ledger) QueryMembers() *LedgerMemberQuery {
	return NewLedgerClient(_m.config).QueryMembers(_m)
}

// Update returns a builder for updating this Ledger.
// Note that you need to call Ledger.Unwrap() before calling this method if this Ledger
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Ledger) Update() *LedgerUpdateOne {
	return NewLedgerClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Ledger entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Ledger) Unwrap() *Ledger {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Ledger is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Ledger) String() string {
	var builder strings.Builder
	builder.WriteString("Ledger(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("channel_id=")
	builder.WriteString(_m.ChannelID)
	builder.WriteString(", ")
	builder.WriteString("guild_id=")
	builder.WriteString(_m.GuildID)
	builder.WriteString(", ")
	builder.WriteString("category_id=")
	builder.WriteString(_m.CategoryID)
	builder.WriteString(", ")
	builder.WriteString("pinned_message_id=")
	builder.WriteString(_m.PinnedMessageID)
	builder.WriteString(", ")
	builder.WriteString("active=")
	builder.WriteString(fmt.Sprintf("%v", _m.Active))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// Ledgers is a parsable slice of Ledger.
type Ledgers []*Ledger
