// Code generated by ent, DO NOT EDIT.

package ent

import (
	"bill-bot/ent/ledger"
	"bill-bot/ent/ledgermember"
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// LedgerMemberCreate is the builder for creating a LedgerMember entity.
type LedgerMemberCreate struct {
	config
	mutation *LedgerMemberMutation
	hooks    []Hook
}

// SetUserID sets the "user_id" field.
func (_c *LedgerMemberCreate) SetUserID(v string) *LedgerMemberCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetUserName sets the "user_name" field.
func (_c *LedgerMemberCreate) SetUserName(v string) *LedgerMemberCreate {
	_c.mutation.SetUserName(v)
	return _c
}

// SetActive sets the "active" field.
func (_c *LedgerMemberCreate) SetActive(v bool) *LedgerMemberCreate {
	_c.mutation.SetActive(v)
	return _c
}

// SetNillableActive sets the "active" field if the given value is not nil.
func (_c *LedgerMemberCreate) SetNillableActive(v *bool) *LedgerMemberCreate {
	if v != nil {
		_c.SetActive(*v)
	}
	return _c
}

// SetJoinedAt sets the "joined_at" field.
func (_c *LedgerMemberCreate) SetJoinedAt(v time.Time) *LedgerMemberCreate {
	_c.mutation.SetJoinedAt(v)
	return _c
}

// SetNillableJoinedAt sets the "joined_at" field if the given value is not nil.
func (_c *LedgerMemberCreate) SetNillableJoinedAt(v *time.Time) *LedgerMemberCreate {
	if v != nil {
		_c.SetJoinedAt(*v)
	}
	return _c
}

// SetLedgerID sets the "ledger" edge to the Ledger entity by ID.
func (_c *LedgerMemberCreate) SetLedgerID(id int) *LedgerMemberCreate {
	_c.mutation.SetLedgerID(id)
	return _c
}

// SetLedger sets the "ledger" edge to the Ledger entity.
func (_c *LedgerMemberCreate) SetLedger(v *Ledger) *LedgerMemberCreate {
	return _c.SetLedgerID(v.ID)
}

// Mutation returns the LedgerMemberMutation object of the builder.
func (_c *LedgerMemberCreate) Mutation() *LedgerMemberMutation {
	return _c.mutation
}

// Save creates the LedgerMember in the database.
func (_c *LedgerMemberCreate) Save(ctx context.Context) (*LedgerMember, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *LedgerMemberCreate) SaveX(ctx context.Context) *LedgerMember {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *LedgerMemberCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *LedgerMemberCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *LedgerMemberCreate) defaults() {
	if _, ok := _c.mutation.Active(); !ok {
		v := ledgermember.DefaultActive
		_c.mutation.SetActive(v)
	}
	if _, ok := _c.mutation.JoinedAt(); !ok {
		v := ledgermember.DefaultJoinedAt()
		_c.mutation.SetJoinedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *LedgerMemberCreate) check() error {
	if _, ok := _c.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "LedgerMember.user_id"`)}
	}
	if _, ok := _c.mutation.UserName(); !ok {
		return &ValidationError{Name: "user_name", err: errors.New(`ent: missing required field "LedgerMember.user_name"`)}
	}
	if _, ok := _c.mutation.Active(); !ok {
		return &ValidationError{Name: "active", err: errors.New(`ent: missing required field "LedgerMember.active"`)}
	}
	if _, ok := _c.mutation.JoinedAt(); !ok {
		return &ValidationError{Name: "joined_at", err: errors.New(`ent: missing required field "LedgerMember.joined_at"`)}
	}
	if len(_c.mutation.LedgerIDs()) == 0 {
		return &ValidationError{Name: "ledger", err: errors.New(`ent: missing required edge "LedgerMember.ledger"`)}
	}
	return nil
}

func (_c *LedgerMemberCreate) sqlSave(ctx context.Context) (*LedgerMember, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *LedgerMemberCreate) createSpec() (*LedgerMember, *sqlgraph.CreateSpec) {
	var (
		_node = &LedgerMember{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(ledgermember.Table, sqlgraph.NewFieldSpec(ledgermember.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.UserID(); ok {
		_spec.SetField(ledgermember.FieldUserID, field.TypeString, value)
		_node.UserID = value
	}
	if value, ok := _c.mutation.UserName(); ok {
		_spec.SetField(ledgermember.FieldUserName, field.TypeString, value)
		_node.UserName = value
	}
	if value, ok := _c.mutation.Active(); ok {
		_spec.SetField(ledgermember.FieldActive, field.TypeBool, value)
		_node.Active = value
	}
	if value, ok := _c.mutation.JoinedAt(); ok {
		_spec.SetField(ledgermember.FieldJoinedAt, field.TypeTime, value)
		_node.JoinedAt = value
	}
	if nodes := _c.mutation.LedgerIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   ledgermember.LedgerTable,
			Columns: []string{ledgermember.LedgerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(ledger.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.ledger_members = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// LedgerMemberCreateBulk is the builder for creating many LedgerMember entities in bulk.
type LedgerMemberCreateBulk struct {
	config
	err      error
	builders []*LedgerMemberCreate
}

// Save creates the LedgerMember entities in the database.
func (_c *LedgerMemberCreateBulk) Save(ctx context.Context) ([]*LedgerMember, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*LedgerMember, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*LedgerMemberMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *LedgerMemberCreateBulk) SaveX(ctx context.Context) []*LedgerMember {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *LedgerMemberCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *LedgerMemberCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
