// Code generated by ent, DO NOT EDIT.

package ent

import (
	"bill-bot/ent/ledger"
	"bill-bot/ent/ledgermember"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// LedgerMember is the model entity for the LedgerMember schema.
type LedgerMember struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// UserID holds the value of the "user_id" field.
	UserID string `json:"user_id,omitempty"`
	// UserName holds the value of the "user_name" field.
	UserName string `json:"user_name,omitempty"`
	// Active holds the value of the "active" field.
	Active bool `json:"active,omitempty"`
	// JoinedAt holds the value of the "joined_at" field.
	JoinedAt time.Time `json:"joined_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the LedgerMemberQuery when eager-loading is set.
	Edges          LedgerMemberEdges `json:"edges"`
	ledger_members *int
	selectValues   sql.SelectValues
}

// LedgerMemberEdges holds the relations/edges for other nodes in the graph.
type LedgerMemberEdges struct {
	// Ledger holds the value of the ledger edge.
	Ledger *Ledger `json:"ledger,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// LedgerOrErr returns the Ledger value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e LedgerMemberEdges) LedgerOrErr() (*Ledger, error) {
	if e.Ledger != nil {
		return e.Ledger, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: ledger.Label}
	}
	return nil, &NotLoadedError{edge: "ledger"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*LedgerMember) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case ledgermember.FieldActive:
			values[i] = new(sql.NullBool)
		case ledgermember.FieldID:
			values[i] = new(sql.NullInt64)
		case ledgermember.FieldUserID, ledgermember.FieldUserName:
			values[i] = new(sql.NullString)
		case ledgermember.FieldJoinedAt:
			values[i] = new(sql.NullTime)
		case ledgermember.ForeignKeys[0]: // ledger_members
			values[i] = new(sql.NullInt64)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the LedgerMember fields.
func (_m *LedgerMember) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case ledgermember.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case ledgermember.FieldUserID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field user_id", values[i])
			} else if value.Valid {
				_m.UserID = value.String
			}
		case ledgermember.FieldUserName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field user_name", values[i])
			} else if value.Valid {
				_m.UserName = value.String
			}
		case ledgermember.FieldActive:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field active", values[i])
			} else if value.Valid {
				_m.Active = value.Bool
			}
		case ledgermember.FieldJoinedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field joined_at", values[i])
			} else if value.Valid {
				_m.JoinedAt = value.Time
			}
		case ledgermember.ForeignKeys[0]:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for edge-field ledger_members", value)
			} else if value.Valid {
				_m.ledger_members = new(int)
				*_m.ledger_members = int(value.Int64)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the LedgerMember.
// This includes values selected through modifiers, order, etc.
func (_m *LedgerMember) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryLedger queries the "ledger" edge of the LedgerMember entity.
func (_m *LedgerMember) QueryLedger() *LedgerQuery {
	return NewLedgerMemberClient(_m.config).QueryLedger(_m)
}

// Update returns a builder for updating this LedgerMember.
// Note that you need to call LedgerMember.Unwrap() before calling this method if this LedgerMember
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *LedgerMember) Update() *LedgerMemberUpdateOne {
	return NewLedgerMemberClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the LedgerMember entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *LedgerMember) Unwrap() *LedgerMember {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: LedgerMember is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *LedgerMember) String() string {
	var builder strings.Builder
	builder.WriteString("LedgerMember(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("user_id=")
	builder.WriteString(_m.UserID)
	builder.WriteString(", ")
	builder.WriteString("user_name=")
	builder.WriteString(_m.UserName)
	builder.WriteString(", ")
	builder.WriteString("active=")
	builder.WriteString(fmt.Sprintf("%v", _m.Active))
	builder.WriteString(", ")
	builder.WriteString("joined_at=")
	builder.WriteString(_m.JoinedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// LedgerMembers is a parsable slice of LedgerMember.
type LedgerMembers []*LedgerMember
