// Code generated by ent, DO NOT EDIT.

package ent

import (
	"bill-bot/ent/expense"
	"bill-bot/ent/ledger"
	"bill-bot/ent/ledgermember"
	"bill-bot/ent/payment"
	"bill-bot/ent/predicate"
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// LedgerUpdate is the builder for updating Ledger entities.
type LedgerUpdate struct {
	config
	hooks    []Hook
	mutation *LedgerMutation
}

// Where appends a list predicates to the LedgerUpdate builder.
func (_u *LedgerUpdate) Where(ps ...predicate.Ledger) *LedgerUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetCategoryID sets the "category_id" field.
func (_u *LedgerUpdate) SetCategoryID(v string) *LedgerUpdate {
	_u.mutation.SetCategoryID(v)
	return _u
}

// SetNillableCategoryID sets the "category_id" field if the given value is not nil.
func (_u *LedgerUpdate) SetNillableCategoryID(v *string) *LedgerUpdate {
	if v != nil {
		_u.SetCategoryID(*v)
	}
	return _u
}

// ClearCategoryID clears the value of the "category_id" field.
func (_u *LedgerUpdate) ClearCategoryID() *LedgerUpdate {
	_u.mutation.ClearCategoryID()
	return _u
}

// SetPinnedMessageID sets the "pinned_message_id" field.
func (_u *LedgerUpdate) SetPinnedMessageID(v string) *LedgerUpdate {
	_u.mutation.SetPinnedMessageID(v)
	return _u
}

// SetNillablePinnedMessageID sets the "pinned_message_id" field if the given value is not nil.
func (_u *LedgerUpdate) SetNillablePinnedMessageID(v *string) *LedgerUpdate {
	if v != nil {
		_u.SetPinnedMessageID(*v)
	}
	return _u
}

// ClearPinnedMessageID clears the value of the "pinned_message_id" field.
func (_u *LedgerUpdate) ClearPinnedMessageID() *LedgerUpdate {
	_u.mutation.ClearPinnedMessageID()
	return _u
}

// SetActive sets the "active" field.
func (_u *LedgerUpdate) SetActive(v bool) *LedgerUpdate {
	_u.mutation.SetActive(v)
	return _u
}

// SetNillableActive sets the "active" field if the given value is not nil.
func (_u *LedgerUpdate) SetNillableActive(v *bool) *LedgerUpdate {
	if v != nil {
		_u.SetActive(*v)
	}
	return _u
}

// AddExpenseIDs adds the "expenses" edge to the Expense entity by IDs.
func (_u *LedgerUpdate) AddExpenseIDs(ids ...int) *LedgerUpdate {
	_u.mutation.AddExpenseIDs(ids...)
	return _u
}

// AddExpenses adds the "expenses" edges to the Expense entity.
func (_u *LedgerUpdate) AddExpenses(v ...*Expense) *LedgerUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddExpenseIDs(ids...)
}

// AddPaymentIDs adds the "payments" edge to the Payment entity by IDs.
func (_u *LedgerUpdate) AddPaymentIDs(ids ...int) *LedgerUpdate {
	_u.mutation.AddPaymentIDs(ids...)
	return _u
}

// AddPayments adds the "payments" edges to the Payment entity.
func (_u *LedgerUpdate) AddPayments(v ...*Payment) *LedgerUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddPaymentIDs(ids...)
}

// AddMemberIDs adds the "members" edge to the LedgerMember entity by IDs.
func (_u *LedgerUpdate) AddMemberIDs(ids ...int) *LedgerUpdate {
	_u.mutation.AddMemberIDs(ids...)
	return _u
}

// AddMembers adds the "members" edges to the LedgerMember entity.
func (_u *LedgerUpdate) AddMembers(v ...*LedgerMember) *LedgerUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddMemberIDs(ids...)
}

// Mutation returns the LedgerMutation object of the builder.
func (_u *LedgerUpdate) Mutation() *LedgerMutation {
	return _u.mutation
}

// ClearExpenses clears all "expenses" edges to the Expense entity.
func (_u *LedgerUpdate) ClearExpenses() *LedgerUpdate {
	_u.mutation.ClearExpenses()
	return _u
}

// RemoveExpenseIDs removes the "expenses" edge to Expense entities by IDs.
func (_u *LedgerUpdate) RemoveExpenseIDs(ids ...int) *LedgerUpdate {
	_u.mutation.RemoveExpenseIDs(ids...)
	return _u
}

// RemoveExpenses removes "expenses" edges to Expense entities.
func (_u *LedgerUpdate) RemoveExpenses(v ...*Expense) *LedgerUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveExpenseIDs(ids...)
}

// ClearPayments clears all "payments" edges to the Payment entity.
func (_u *LedgerUpdate) ClearPayments() *LedgerUpdate {
	_u.mutation.ClearPayments()
	return _u
}

// RemovePaymentIDs removes the "payments" edge to Payment entities by IDs.
func (_u *LedgerUpdate) RemovePaymentIDs(ids ...int) *LedgerUpdate {
	_u.mutation.RemovePaymentIDs(ids...)
	return _u
}

// RemovePayments removes "payments" edges to Payment entities.
func (_u *LedgerUpdate) RemovePayments(v ...*Payment) *LedgerUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemovePaymentIDs(ids...)
}

// ClearMembers clears all "members" edges to the LedgerMember entity.
func (_u *LedgerUpdate) ClearMembers() *LedgerUpdate {
	_u.mutation.ClearMembers()
	return _u
}

// RemoveMemberIDs removes the "members" edge to LedgerMember entities by IDs.
func (_u *LedgerUpdate) RemoveMemberIDs(ids ...int) *LedgerUpdate {
	_u.mutation.RemoveMemberIDs(ids...)
	return _u
}

// RemoveMembers removes "members" edges to LedgerMember entities.
func (_u *LedgerUpdate) RemoveMembers(v ...*LedgerMember) *LedgerUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveMemberIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *LedgerUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *LedgerUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *LedgerUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *LedgerUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *LedgerUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(ledger.Table, ledger.Columns, sqlgraph.NewFieldSpec(ledger.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.CategoryID(); ok {
		_spec.SetField(ledger.FieldCategoryID, field.TypeString, value)
	}
	if _u.mutation.CategoryIDCleared() {
		_spec.ClearField(ledger.FieldCategoryID, field.TypeString)
	}
	if value, ok := _u.mutation.PinnedMessageID(); ok {
		_spec.SetField(ledger.FieldPinnedMessageID, field.TypeString, value)
	}
	if _u.mutation.PinnedMessageIDCleared() {
		_spec.ClearField(ledger.FieldPinnedMessageID, field.TypeString)
	}
	if value, ok := _u.mutation.Active(); ok {
		_spec.SetField(ledger.FieldActive, field.TypeBool, value)
	}
	if _u.mutation.ExpensesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   ledger.ExpensesTable,
			Columns: []string{ledger.ExpensesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(expense.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedExpensesIDs(); len(nodes) > 0 && !_u.mutation.ExpensesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   ledger.ExpensesTable,
			Columns: []string{ledger.ExpensesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(expense.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ExpensesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   ledger.ExpensesTable,
			Columns: []string{ledger.ExpensesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(expense.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.PaymentsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   ledger.PaymentsTable,
			Columns: []string{ledger.PaymentsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(payment.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedPaymentsIDs(); len(nodes) > 0 && !_u.mutation.PaymentsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   ledger.PaymentsTable,
			Columns: []string{ledger.PaymentsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(payment.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.PaymentsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   ledger.PaymentsTable,
			Columns: []string{ledger.PaymentsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(payment.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.MembersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   ledger.MembersTable,
			Columns: []string{ledger.MembersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(ledgermember.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedMembersIDs(); len(nodes) > 0 && !_u.mutation.MembersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   ledger.MembersTable,
			Columns: []string{ledger.MembersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(ledgermember.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.MembersIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   ledger.MembersTable,
			Columns: []string{ledger.MembersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(ledgermember.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{ledger.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// LedgerUpdateOne is the builder for updating a single Ledger entity.
type LedgerUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *LedgerMutation
}

// SetCategoryID sets the "category_id" field.
func (_u *LedgerUpdateOne) SetCategoryID(v string) *LedgerUpdateOne {
	_u.mutation.SetCategoryID(v)
	return _u
}

// SetNillableCategoryID sets the "category_id" field if the given value is not nil.
func (_u *LedgerUpdateOne) SetNillableCategoryID(v *string) *LedgerUpdateOne {
	if v != nil {
		_u.SetCategoryID(*v)
	}
	return _u
}

// ClearCategoryID clears the value of the "category_id" field.
func (_u *LedgerUpdateOne) ClearCategoryID() *LedgerUpdateOne {
	_u.mutation.ClearCategoryID()
	return _u
}

// SetPinnedMessageID sets the "pinned_message_id" field.
func (_u *LedgerUpdateOne) SetPinnedMessageID(v string) *LedgerUpdateOne {
	_u.mutation.SetPinnedMessageID(v)
	return _u
}

// SetNillablePinnedMessageID sets the "pinned_message_id" field if the given value is not nil.
func (_u *LedgerUpdateOne) SetNillablePinnedMessageID(v *string) *LedgerUpdateOne {
	if v != nil {
		_u.SetPinnedMessageID(*v)
	}
	return _u
}

// ClearPinnedMessageID clears the value of the "pinned_message_id" field.
func (_u *LedgerUpdateOne) ClearPinnedMessageID() *LedgerUpdateOne {
	_u.mutation.ClearPinnedMessageID()
	return _u
}

// SetActive sets the "active" field.
func (_u *LedgerUpdateOne) SetActive(v bool) *LedgerUpdateOne {
	_u.mutation.SetActive(v)
	return _u
}

// SetNillableActive sets the "active" field if the given value is not nil.
func (_u *LedgerUpdateOne) SetNillableActive(v *bool) *LedgerUpdateOne {
	if v != nil {
		_u.SetActive(*v)
	}
	return _u
}

// AddExpenseIDs adds the "expenses" edge to the Expense entity by IDs.
func (_u *LedgerUpdateOne) AddExpenseIDs(ids ...int) *LedgerUpdateOne {
	_u.mutation.AddExpenseIDs(ids...)
	return _u
}

// AddExpenses adds the "expenses" edges to the Expense entity.
func (_u *LedgerUpdateOne) AddExpenses(v ...*Expense) *LedgerUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddExpenseIDs(ids...)
}

// AddPaymentIDs adds the "payments" edge to the Payment entity by IDs.
func (_u *LedgerUpdateOne) AddPaymentIDs(ids ...int) *LedgerUpdateOne {
	_u.mutation.AddPaymentIDs(ids...)
	return _u
}

// AddPayments adds the "payments" edges to the Payment entity.
func (_u *LedgerUpdateOne) AddPayments(v ...*Payment) *LedgerUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddPaymentIDs(ids...)
}

// AddMemberIDs adds the "members" edge to the LedgerMember entity by IDs.
func (_u *LedgerUpdateOne) AddMemberIDs(ids ...int) *LedgerUpdateOne {
	_u.mutation.AddMemberIDs(ids...)
	return _u
}

// AddMembers adds the "members" edges to the LedgerMember entity.
func (_u *LedgerUpdateOne) AddMembers(v ...*LedgerMember) *LedgerUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddMemberIDs(ids...)
}

// Mutation returns the LedgerMutation object of the builder.
func (_u *LedgerUpdateOne) Mutation() *LedgerMutation {
	return _u.mutation
}

// ClearExpenses clears all "expenses" edges to the Expense entity.
func (_u *LedgerUpdateOne) ClearExpenses() *LedgerUpdateOne {
	_u.mutation.ClearExpenses()
	return _u
}

// RemoveExpenseIDs removes the "expenses" edge to Expense entities by IDs.
func (_u *LedgerUpdateOne) RemoveExpenseIDs(ids ...int) *LedgerUpdateOne {
	_u.mutation.RemoveExpenseIDs(ids...)
	return _u
}

// RemoveExpenses removes "expenses" edges to Expense entities.
func (_u *LedgerUpdateOne) RemoveExpenses(v ...*Expense) *LedgerUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveExpenseIDs(ids...)
}

// ClearPayments clears all "payments" edges to the Payment entity.
func (_u *LedgerUpdateOne) ClearPayments() *LedgerUpdateOne {
	_u.mutation.ClearPayments()
	return _u
}

// RemovePaymentIDs removes the "payments" edge to Payment entities by IDs.
func (_u *LedgerUpdateOne) RemovePaymentIDs(ids ...int) *LedgerUpdateOne {
	_u.mutation.RemovePaymentIDs(ids...)
	return _u
}

// RemovePayments removes "payments" edges to Payment entities.
func (_u *LedgerUpdateOne) RemovePayments(v ...*Payment) *LedgerUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemovePaymentIDs(ids...)
}

// ClearMembers clears all "members" edges to the LedgerMember entity.
func (_u *LedgerUpdateOne) ClearMembers() *LedgerUpdateOne {
	_u.mutation.ClearMembers()
	return _u
}

// RemoveMemberIDs removes the "members" edge to LedgerMember entities by IDs.
func (_u *LedgerUpdateOne) RemoveMemberIDs(ids ...int) *LedgerUpdateOne {
	_u.mutation.RemoveMemberIDs(ids...)
	return _u
}

// RemoveMembers removes "members" edges to LedgerMember entities.
func (_u *LedgerUpdateOne) RemoveMembers(v ...*LedgerMember) *LedgerUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveMemberIDs(ids...)
}

// Where appends a list predicates to the LedgerUpdate builder.
func (_u *LedgerUpdateOne) Where(ps ...predicate.Ledger) *LedgerUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *LedgerUpdateOne) Select(field string, fields ...string) *LedgerUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Ledger entity.
func (_u *LedgerUpdateOne) Save(ctx context.Context) (*Ledger, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *LedgerUpdateOne) SaveX(ctx context.Context) *Ledger {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *LedgerUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *LedgerUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *LedgerUpdateOne) sqlSave(ctx context.Context) (_node *Ledger, err error) {
	_spec := sqlgraph.NewUpdateSpec(ledger.Table, ledger.Columns, sqlgraph.NewFieldSpec(ledger.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Ledger.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, ledger.FieldID)
		for _, f := range fields {
			if !ledger.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != ledger.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.CategoryID(); ok {
		_spec.SetField(ledger.FieldCategoryID, field.TypeString, value)
	}
	if _u.mutation.CategoryIDCleared() {
		_spec.ClearField(ledger.FieldCategoryID, field.TypeString)
	}
	if value, ok := _u.mutation.PinnedMessageID(); ok {
		_spec.SetField(ledger.FieldPinnedMessageID, field.TypeString, value)
	}
	if _u.mutation.PinnedMessageIDCleared() {
		_spec.ClearField(ledger.FieldPinnedMessageID, field.TypeString)
	}
	if value, ok := _u.mutation.Active(); ok {
		_spec.SetField(ledger.FieldActive, field.TypeBool, value)
	}
	if _u.mutation.ExpensesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   ledger.ExpensesTable,
			Columns: []string{ledger.ExpensesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(expense.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedExpensesIDs(); len(nodes) > 0 && !_u.mutation.ExpensesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   ledger.ExpensesTable,
			Columns: []string{ledger.ExpensesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(expense.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ExpensesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   ledger.ExpensesTable,
			Columns: []string{ledger.ExpensesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(expense.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.PaymentsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   ledger.PaymentsTable,
			Columns: []string{ledger.PaymentsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(payment.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedPaymentsIDs(); len(nodes) > 0 && !_u.mutation.PaymentsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   ledger.PaymentsTable,
			Columns: []string{ledger.PaymentsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(payment.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.PaymentsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   ledger.PaymentsTable,
			Columns: []string{ledger.PaymentsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(payment.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.MembersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   ledger.MembersTable,
			Columns: []string{ledger.MembersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(ledgermember.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedMembersIDs(); len(nodes) > 0 && !_u.mutation.MembersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   ledger.MembersTable,
			Columns: []string{ledger.MembersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(ledgermember.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.MembersIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   ledger.MembersTable,
			Columns: []string{ledger.MembersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(ledgermember.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Ledger{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{ledger.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
