// Code generated by ent, DO NOT EDIT.

package ent

import (
	"bill-bot/ent/ledger"
	"bill-bot/ent/payment"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// Payment is the model entity for the Payment schema.
type Payment struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// FromUserID holds the value of the "from_user_id" field.
	FromUserID string `json:"from_user_id,omitempty"`
	// FromUserName holds the value of the "from_user_name" field.
	FromUserName string `json:"from_user_name,omitempty"`
	// ToUserID holds the value of the "to_user_id" field.
	ToUserID string `json:"to_user_id,omitempty"`
	// ToUserName holds the value of the "to_user_name" field.
	ToUserName string `json:"to_user_name,omitempty"`
	// Amount holds the value of the "amount" field.
	Amount int64 `json:"amount,omitempty"`
	// Note holds the value of the "note" field.
	Note string `json:"note,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the PaymentQuery when eager-loading is set.
	Edges           PaymentEdges `json:"edges"`
	ledger_payments *int
	selectValues    sql.SelectValues
}

// PaymentEdges holds the relations/edges for other nodes in the graph.
type PaymentEdges struct {
	// Ledger holds the value of the ledger edge.
	Ledger *Ledger `json:"ledger,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// LedgerOrErr returns the Ledger value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e PaymentEdges) LedgerOrErr() (*Ledger, error) {
	if e.Ledger != nil {
		return e.Ledger, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: ledger.Label}
	}
	return nil, &NotLoadedError{edge: "ledger"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Payment) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case payment.FieldID, payment.FieldAmount:
			values[i] = new(sql.NullInt64)
		case payment.FieldFromUserID, payment.FieldFromUserName, payment.FieldToUserID, payment.FieldToUserName, payment.FieldNote:
			values[i] = new(sql.NullString)
		case payment.FieldCreatedAt:
			values[i] = new(sql.NullTime)
		case payment.ForeignKeys[0]: // ledger_payments
			values[i] = new(sql.NullInt64)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Payment fields.
func (_m *Payment) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case payment.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case payment.FieldFromUserID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field from_user_id", values[i])
			} else if value.Valid {
				_m.FromUserID = value.String
			}
		case payment.FieldFromUserName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field from_user_name", values[i])
			} else if value.Valid {
				_m.FromUserName = value.String
			}
		case payment.FieldToUserID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field to_user_id", values[i])
			} else if value.Valid {
				_m.ToUserID = value.String
			}
		case payment.FieldToUserName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field to_user_name", values[i])
			} else if value.Valid {
				_m.ToUserName = value.String
			}
		case payment.FieldAmount:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field amount", values[i])
			} else if value.Valid {
				_m.Amount = value.Int64
			}
		case payment.FieldNote:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field note", values[i])
			} else if value.Valid {
				_m.Note = value.String
			}
		case payment.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case payment.ForeignKeys[0]:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for edge-field ledger_payments", value)
			} else if value.Valid {
				_m.ledger_payments = new(int)
				*_m.ledger_payments = int(value.Int64)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Payment.
// This includes values selected through modifiers, order, etc.
func (_m *Payment) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryLedger queries the "ledger" edge of the Payment entity.
func (_m *Payment) QueryLedger() *LedgerQuery {
	return NewPaymentClient(_m.config).QueryLedger(_m)
}

// Update returns a builder for updating this Payment.
// Note that you need to call Payment.Unwrap() before calling this method if this Payment
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Payment) Update() *PaymentUpdateOne {
	return NewPaymentClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Payment entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Payment) Unwrap() *Payment {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Payment is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Payment) String() string {
	var builder strings.Builder
	builder.WriteString("Payment(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("from_user_id=")
	builder.WriteString(_m.FromUserID)
	builder.WriteString(", ")
	builder.WriteString("from_user_name=")
	builder.WriteString(_m.FromUserName)
	builder.WriteString(", ")
	builder.WriteString("to_user_id=")
	builder.WriteString(_m.ToUserID)
	builder.WriteString(", ")
	builder.WriteString("to_user_name=")
	builder.WriteString(_m.ToUserName)
	builder.WriteString(", ")
	builder.WriteString("amount=")
	builder.WriteString(fmt.Sprintf("%v", _m.Amount))
	builder.WriteString(", ")
	builder.WriteString("note=")
	builder.WriteString(_m.Note)
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// Payments is a parsable slice of Payment.
type Payments []*Payment
