// Code generated by ent, DO NOT EDIT.

package ent

import (
	"bill-bot/ent/ledger"
	"bill-bot/ent/payment"
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// PaymentCreate is the builder for creating a Payment entity.
type PaymentCreate struct {
	config
	mutation *PaymentMutation
	hooks    []Hook
}

// SetFromUserID sets the "from_user_id" field.
func (_c *PaymentCreate) SetFromUserID(v string) *PaymentCreate {
	_c.mutation.SetFromUserID(v)
	return _c
}

// SetFromUserName sets the "from_user_name" field.
func (_c *PaymentCreate) SetFromUserName(v string) *PaymentCreate {
	_c.mutation.SetFromUserName(v)
	return _c
}

// SetToUserID sets the "to_user_id" field.
func (_c *PaymentCreate) SetToUserID(v string) *PaymentCreate {
	_c.mutation.SetToUserID(v)
	return _c
}

// SetToUserName sets the "to_user_name" field.
func (_c *PaymentCreate) SetToUserName(v string) *PaymentCreate {
	_c.mutation.SetToUserName(v)
	return _c
}

// SetAmount sets the "amount" field.
func (_c *PaymentCreate) SetAmount(v int64) *PaymentCreate {
	_c.mutation.SetAmount(v)
	return _c
}

// SetNote sets the "note" field.
func (_c *PaymentCreate) SetNote(v string) *PaymentCreate {
	_c.mutation.SetNote(v)
	return _c
}

// SetNillableNote sets the "note" field if the given value is not nil.
func (_c *PaymentCreate) SetNillableNote(v *string) *PaymentCreate {
	if v != nil {
		_c.SetNote(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *PaymentCreate) SetCreatedAt(v time.Time) *PaymentCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *PaymentCreate) SetNillableCreatedAt(v *time.Time) *PaymentCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetLedgerID sets the "ledger" edge to the Ledger entity by ID.
func (_c *PaymentCreate) SetLedgerID(id int) *PaymentCreate {
	_c.mutation.SetLedgerID(id)
	return _c
}

// SetLedger sets the "ledger" edge to the Ledger entity.
func (_c *PaymentCreate) SetLedger(v *Ledger) *PaymentCreate {
	return _c.SetLedgerID(v.ID)
}

// Mutation returns the PaymentMutation object of the builder.
func (_c *PaymentCreate) Mutation() *PaymentMutation {
	return _c.mutation
}

// Save creates the Payment in the database.
func (_c *PaymentCreate) Save(ctx context.Context) (*Payment, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *PaymentCreate) SaveX(ctx context.Context) *Payment {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *PaymentCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *PaymentCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *PaymentCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := payment.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *PaymentCreate) check() error {
	if _, ok := _c.mutation.FromUserID(); !ok {
		return &ValidationError{Name: "from_user_id", err: errors.New(`ent: missing required field "Payment.from_user_id"`)}
	}
	if _, ok := _c.mutation.FromUserName(); !ok {
		return &ValidationError{Name: "from_user_name", err: errors.New(`ent: missing required field "Payment.from_user_name"`)}
	}
	if _, ok := _c.mutation.ToUserID(); !ok {
		return &ValidationError{Name: "to_user_id", err: errors.New(`ent: missing required field "Payment.to_user_id"`)}
	}
	if _, ok := _c.mutation.ToUserName(); !ok {
		return &ValidationError{Name: "to_user_name", err: errors.New(`ent: missing required field "Payment.to_user_name"`)}
	}
	if _, ok := _c.mutation.Amount(); !ok {
		return &ValidationError{Name: "amount", err: errors.New(`ent: missing required field "Payment.amount"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Payment.created_at"`)}
	}
	if len(_c.mutation.LedgerIDs()) == 0 {
		return &ValidationError{Name: "ledger", err: errors.New(`ent: missing required edge "Payment.ledger"`)}
	}
	return nil
}

func (_c *PaymentCreate) sqlSave(ctx context.Context) (*Payment, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *PaymentCreate) createSpec() (*Payment, *sqlgraph.CreateSpec) {
	var (
		_node = &Payment{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(payment.Table, sqlgraph.NewFieldSpec(payment.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.FromUserID(); ok {
		_spec.SetField(payment.FieldFromUserID, field.TypeString, value)
		_node.FromUserID = value
	}
	if value, ok := _c.mutation.FromUserName(); ok {
		_spec.SetField(payment.FieldFromUserName, field.TypeString, value)
		_node.FromUserName = value
	}
	if value, ok := _c.mutation.ToUserID(); ok {
		_spec.SetField(payment.FieldToUserID, field.TypeString, value)
		_node.ToUserID = value
	}
	if value, ok := _c.mutation.ToUserName(); ok {
		_spec.SetField(payment.FieldToUserName, field.TypeString, value)
		_node.ToUserName = value
	}
	if value, ok := _c.mutation.Amount(); ok {
		_spec.SetField(payment.FieldAmount, field.TypeInt64, value)
		_node.Amount = value
	}
	if value, ok := _c.mutation.Note(); ok {
		_spec.SetField(payment.FieldNote, field.TypeString, value)
		_node.Note = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(payment.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if nodes := _c.mutation.LedgerIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   payment.LedgerTable,
			Columns: []string{payment.LedgerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(ledger.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.ledger_payments = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// PaymentCreateBulk is the builder for creating many Payment entities in bulk.
type PaymentCreateBulk struct {
	config
	err      error
	builders []*PaymentCreate
}

// Save creates the Payment entities in the database.
func (_c *PaymentCreateBulk) Save(ctx context.Context) ([]*Payment, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Payment, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*PaymentMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *PaymentCreateBulk) SaveX(ctx context.Context) []*Payment {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *PaymentCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *PaymentCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
