// Code generated by ent, DO NOT EDIT.

package ent

import (
	"bill-bot/ent/ledger"
	"bill-bot/ent/payment"
	"bill-bot/ent/predicate"
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// PaymentUpdate is the builder for updating Payment entities.
type PaymentUpdate struct {
	config
	hooks    []Hook
	mutation *PaymentMutation
}

// Where appends a list predicates to the PaymentUpdate builder.
func (_u *PaymentUpdate) Where(ps ...predicate.Payment) *PaymentUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetFromUserID sets the "from_user_id" field.
func (_u *PaymentUpdate) SetFromUserID(v string) *PaymentUpdate {
	_u.mutation.SetFromUserID(v)
	return _u
}

// SetNillableFromUserID sets the "from_user_id" field if the given value is not nil.
func (_u *PaymentUpdate) SetNillableFromUserID(v *string) *PaymentUpdate {
	if v != nil {
		_u.SetFromUserID(*v)
	}
	return _u
}

// SetFromUserName sets the "from_user_name" field.
func (_u *PaymentUpdate) SetFromUserName(v string) *PaymentUpdate {
	_u.mutation.SetFromUserName(v)
	return _u
}

// SetNillableFromUserName sets the "from_user_name" field if the given value is not nil.
func (_u *PaymentUpdate) SetNillableFromUserName(v *string) *PaymentUpdate {
	if v != nil {
		_u.SetFromUserName(*v)
	}
	return _u
}

// SetToUserID sets the "to_user_id" field.
func (_u *PaymentUpdate) SetToUserID(v string) *PaymentUpdate {
	_u.mutation.SetToUserID(v)
	return _u
}

// SetNillableToUserID sets the "to_user_id" field if the given value is not nil.
func (_u *PaymentUpdate) SetNillableToUserID(v *string) *PaymentUpdate {
	if v != nil {
		_u.SetToUserID(*v)
	}
	return _u
}

// SetToUserName sets the "to_user_name" field.
func (_u *PaymentUpdate) SetToUserName(v string) *PaymentUpdate {
	_u.mutation.SetToUserName(v)
	return _u
}

// SetNillableToUserName sets the "to_user_name" field if the given value is not nil.
func (_u *PaymentUpdate) SetNillableToUserName(v *string) *PaymentUpdate {
	if v != nil {
		_u.SetToUserName(*v)
	}
	return _u
}

// SetAmount sets the "amount" field.
func (_u *PaymentUpdate) SetAmount(v int64) *PaymentUpdate {
	_u.mutation.ResetAmount()
	_u.mutation.SetAmount(v)
	return _u
}

// SetNillableAmount sets the "amount" field if the given value is not nil.
func (_u *PaymentUpdate) SetNillableAmount(v *int64) *PaymentUpdate {
	if v != nil {
		_u.SetAmount(*v)
	}
	return _u
}

// AddAmount adds value to the "amount" field.
func (_u *PaymentUpdate) AddAmount(v int64) *PaymentUpdate {
	_u.mutation.AddAmount(v)
	return _u
}

// SetNote sets the "note" field.
func (_u *PaymentUpdate) SetNote(v string) *PaymentUpdate {
	_u.mutation.SetNote(v)
	return _u
}

// SetNillableNote sets the "note" field if the given value is not nil.
func (_u *PaymentUpdate) SetNillableNote(v *string) *PaymentUpdate {
	if v != nil {
		_u.SetNote(*v)
	}
	return _u
}

// ClearNote clears the value of the "note" field.
func (_u *PaymentUpdate) ClearNote() *PaymentUpdate {
	_u.mutation.ClearNote()
	return _u
}

// SetLedgerID sets the "ledger" edge to the Ledger entity by ID.
func (_u *PaymentUpdate) SetLedgerID(id int) *PaymentUpdate {
	_u.mutation.SetLedgerID(id)
	return _u
}

// SetLedger sets the "ledger" edge to the Ledger entity.
func (_u *PaymentUpdate) SetLedger(v *Ledger) *PaymentUpdate {
	return _u.SetLedgerID(v.ID)
}

// Mutation returns the PaymentMutation object of the builder.
func (_u *PaymentUpdate) Mutation() *PaymentMutation {
	return _u.mutation
}

// ClearLedger clears the "ledger" edge to the Ledger entity.
func (_u *PaymentUpdate) ClearLedger() *PaymentUpdate {
	_u.mutation.ClearLedger()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *PaymentUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *PaymentUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *PaymentUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *PaymentUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *PaymentUpdate) check() error {
	if _u.mutation.LedgerCleared() && len(_u.mutation.LedgerIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Payment.ledger"`)
	}
	return nil
}

func (_u *PaymentUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(payment.Table, payment.Columns, sqlgraph.NewFieldSpec(payment.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.FromUserID(); ok {
		_spec.SetField(payment.FieldFromUserID, field.TypeString, value)
	}
	if value, ok := _u.mutation.FromUserName(); ok {
		_spec.SetField(payment.FieldFromUserName, field.TypeString, value)
	}
	if value, ok := _u.mutation.ToUserID(); ok {
		_spec.SetField(payment.FieldToUserID, field.TypeString, value)
	}
	if value, ok := _u.mutation.ToUserName(); ok {
		_spec.SetField(payment.FieldToUserName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Amount(); ok {
		_spec.SetField(payment.FieldAmount, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedAmount(); ok {
		_spec.AddField(payment.FieldAmount, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.Note(); ok {
		_spec.SetField(payment.FieldNote, field.TypeString, value)
	}
	if _u.mutation.NoteCleared() {
		_spec.ClearField(payment.FieldNote, field.TypeString)
	}
	if _u.mutation.LedgerCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   payment.LedgerTable,
			Columns: []string{payment.LedgerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(ledger.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.LedgerIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   payment.LedgerTable,
			Columns: []string{payment.LedgerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(ledger.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{payment.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// PaymentUpdateOne is the builder for updating a single Payment entity.
type PaymentUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *PaymentMutation
}

// SetFromUserID sets the "from_user_id" field.
func (_u *PaymentUpdateOne) SetFromUserID(v string) *PaymentUpdateOne {
	_u.mutation.SetFromUserID(v)
	return _u
}

// SetNillableFromUserID sets the "from_user_id" field if the given value is not nil.
func (_u *PaymentUpdateOne) SetNillableFromUserID(v *string) *PaymentUpdateOne {
	if v != nil {
		_u.SetFromUserID(*v)
	}
	return _u
}

// SetFromUserName sets the "from_user_name" field.
func (_u *PaymentUpdateOne) SetFromUserName(v string) *PaymentUpdateOne {
	_u.mutation.SetFromUserName(v)
	return _u
}

// SetNillableFromUserName sets the "from_user_name" field if the given value is not nil.
func (_u *PaymentUpdateOne) SetNillableFromUserName(v *string) *PaymentUpdateOne {
	if v != nil {
		_u.SetFromUserName(*v)
	}
	return _u
}

// SetToUserID sets the "to_user_id" field.
func (_u *PaymentUpdateOne) SetToUserID(v string) *PaymentUpdateOne {
	_u.mutation.SetToUserID(v)
	return _u
}

// SetNillableToUserID sets the "to_user_id" field if the given value is not nil.
func (_u *PaymentUpdateOne) SetNillableToUserID(v *string) *PaymentUpdateOne {
	if v != nil {
		_u.SetToUserID(*v)
	}
	return _u
}

// SetToUserName sets the "to_user_name" field.
func (_u *PaymentUpdateOne) SetToUserName(v string) *PaymentUpdateOne {
	_u.mutation.SetToUserName(v)
	return _u
}

// SetNillableToUserName sets the "to_user_name" field if the given value is not nil.
func (_u *PaymentUpdateOne) SetNillableToUserName(v *string) *PaymentUpdateOne {
	if v != nil {
		_u.SetToUserName(*v)
	}
	return _u
}

// SetAmount sets the "amount" field.
func (_u *PaymentUpdateOne) SetAmount(v int64) *PaymentUpdateOne {
	_u.mutation.ResetAmount()
	_u.mutation.SetAmount(v)
	return _u
}

// SetNillableAmount sets the "amount" field if the given value is not nil.
func (_u *PaymentUpdateOne) SetNillableAmount(v *int64) *PaymentUpdateOne {
	if v != nil {
		_u.SetAmount(*v)
	}
	return _u
}

// AddAmount adds value to the "amount" field.
func (_u *PaymentUpdateOne) AddAmount(v int64) *PaymentUpdateOne {
	_u.mutation.AddAmount(v)
	return _u
}

// SetNote sets the "note" field.
func (_u *PaymentUpdateOne) SetNote(v string) *PaymentUpdateOne {
	_u.mutation.SetNote(v)
	return _u
}

// SetNillableNote sets the "note" field if the given value is not nil.
func (_u *PaymentUpdateOne) SetNillableNote(v *string) *PaymentUpdateOne {
	if v != nil {
		_u.SetNote(*v)
	}
	return _u
}

// ClearNote clears the value of the "note" field.
func (_u *PaymentUpdateOne) ClearNote() *PaymentUpdateOne {
	_u.mutation.ClearNote()
	return _u
}

// SetLedgerID sets the "ledger" edge to the Ledger entity by ID.
func (_u *PaymentUpdateOne) SetLedgerID(id int) *PaymentUpdateOne {
	_u.mutation.SetLedgerID(id)
	return _u
}

// SetLedger sets the "ledger" edge to the Ledger entity.
func (_u *PaymentUpdateOne) SetLedger(v *Ledger) *PaymentUpdateOne {
	return _u.SetLedgerID(v.ID)
}

// Mutation returns the PaymentMutation object of the builder.
func (_u *PaymentUpdateOne) Mutation() *PaymentMutation {
	return _u.mutation
}

// ClearLedger clears the "ledger" edge to the Ledger entity.
func (_u *PaymentUpdateOne) ClearLedger() *PaymentUpdateOne {
	_u.mutation.ClearLedger()
	return _u
}

// Where appends a list predicates to the PaymentUpdate builder.
func (_u *PaymentUpdateOne) Where(ps ...predicate.Payment) *PaymentUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *PaymentUpdateOne) Select(field string, fields ...string) *PaymentUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Payment entity.
func (_u *PaymentUpdateOne) Save(ctx context.Context) (*Payment, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *PaymentUpdateOne) SaveX(ctx context.Context) *Payment {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *PaymentUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *PaymentUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *PaymentUpdateOne) check() error {
	if _u.mutation.LedgerCleared() && len(_u.mutation.LedgerIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Payment.ledger"`)
	}
	return nil
}

func (_u *PaymentUpdateOne) sqlSave(ctx context.Context) (_node *Payment, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(payment.Table, payment.Columns, sqlgraph.NewFieldSpec(payment.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Payment.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, payment.FieldID)
		for _, f := range fields {
			if !payment.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != payment.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.FromUserID(); ok {
		_spec.SetField(payment.FieldFromUserID, field.TypeString, value)
	}
	if value, ok := _u.mutation.FromUserName(); ok {
		_spec.SetField(payment.FieldFromUserName, field.TypeString, value)
	}
	if value, ok := _u.mutation.ToUserID(); ok {
		_spec.SetField(payment.FieldToUserID, field.TypeString, value)
	}
	if value, ok := _u.mutation.ToUserName(); ok {
		_spec.SetField(payment.FieldToUserName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Amount(); ok {
		_spec.SetField(payment.FieldAmount, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedAmount(); ok {
		_spec.AddField(payment.FieldAmount, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.Note(); ok {
		_spec.SetField(payment.FieldNote, field.TypeString, value)
	}
	if _u.mutation.NoteCleared() {
		_spec.ClearField(payment.FieldNote, field.TypeString)
	}
	if _u.mutation.LedgerCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   payment.LedgerTable,
			Columns: []string{payment.LedgerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(ledger.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.LedgerIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   payment.LedgerTable,
			Columns: []string{payment.LedgerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(ledger.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Payment{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{payment.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
