// Code generated by ent, DO NOT EDIT.

package ent

import (
	"bill-bot/ent/expense"
	"bill-bot/ent/ledger"
	"bill-bot/ent/ledgermember"
	"bill-bot/ent/payment"
	"bill-bot/ent/schema"
	"bill-bot/ent/split"
	"time"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	expenseFields := schema.Expense{}.Fields()
	_ = expenseFields
	// expenseDescCurrency is the schema descriptor for currency field.
	expenseDescCurrency := expenseFields[1].Descriptor()
	// expense.DefaultCurrency holds the default value on creation for the currency field.
	expense.DefaultCurrency = expenseDescCurrency.Default.(string)
	// expenseDescDeleted is the schema descriptor for deleted field.
	expenseDescDeleted := expenseFields[5].Descriptor()
	// expense.DefaultDeleted holds the default value on creation for the deleted field.
	expense.DefaultDeleted = expenseDescDeleted.Default.(bool)
	// expenseDescCreatedAt is the schema descriptor for created_at field.
	expenseDescCreatedAt := expenseFields[6].Descriptor()
	// expense.DefaultCreatedAt holds the default value on creation for the created_at field.
	expense.DefaultCreatedAt = expenseDescCreatedAt.Default.(func() time.Time)
	ledgerFields := schema.Ledger{}.Fields()
	_ = ledgerFields
	// ledgerDescActive is the schema descriptor for active field.
	ledgerDescActive := ledgerFields[4].Descriptor()
	// ledger.DefaultActive holds the default value on creation for the active field.
	ledger.DefaultActive = ledgerDescActive.Default.(bool)
	// ledgerDescCreatedAt is the schema descriptor for created_at field.
	ledgerDescCreatedAt := ledgerFields[5].Descriptor()
	// ledger.DefaultCreatedAt holds the default value on creation for the created_at field.
	ledger.DefaultCreatedAt = ledgerDescCreatedAt.Default.(func() time.Time)
	ledgermemberFields := schema.LedgerMember{}.Fields()
	_ = ledgermemberFields
	// ledgermemberDescActive is the schema descriptor for active field.
	ledgermemberDescActive := ledgermemberFields[2].Descriptor()
	// ledgermember.DefaultActive holds the default value on creation for the active field.
	ledgermember.DefaultActive = ledgermemberDescActive.Default.(bool)
	// ledgermemberDescJoinedAt is the schema descriptor for joined_at field.
	ledgermemberDescJoinedAt := ledgermemberFields[3].Descriptor()
	// ledgermember.DefaultJoinedAt holds the default value on creation for the joined_at field.
	ledgermember.DefaultJoinedAt = ledgermemberDescJoinedAt.Default.(func() time.Time)
	paymentFields := schema.Payment{}.Fields()
	_ = paymentFields
	// paymentDescCreatedAt is the schema descriptor for created_at field.
	paymentDescCreatedAt := paymentFields[6].Descriptor()
	// payment.DefaultCreatedAt holds the default value on creation for the created_at field.
	payment.DefaultCreatedAt = paymentDescCreatedAt.Default.(func() time.Time)
	splitFields := schema.Split{}.Fields()
	_ = splitFields
	// splitDescSettled is the schema descriptor for settled field.
	splitDescSettled := splitFields[2].Descriptor()
	// split.DefaultSettled holds the default value on creation for the settled field.
	split.DefaultSettled = splitDescSettled.Default.(bool)
}
