// Code generated by ent, DO NOT EDIT.

package ent

import (
	"bill-bot/ent/expense"
	"bill-bot/ent/split"
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// SplitCreate is the builder for creating a Split entity.
type SplitCreate struct {
	config
	mutation *SplitMutation
	hooks    []Hook
}

// SetUserID sets the "user_id" field.
func (_c *SplitCreate) SetUserID(v string) *SplitCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetAmount sets the "amount" field.
func (_c *SplitCreate) SetAmount(v int64) *SplitCreate {
	_c.mutation.SetAmount(v)
	return _c
}

// SetSettled sets the "settled" field.
func (_c *SplitCreate) SetSettled(v bool) *SplitCreate {
	_c.mutation.SetSettled(v)
	return _c
}

// SetNillableSettled sets the "settled" field if the given value is not nil.
func (_c *SplitCreate) SetNillableSettled(v *bool) *SplitCreate {
	if v != nil {
		_c.SetSettled(*v)
	}
	return _c
}

// SetExpenseID sets the "expense" edge to the Expense entity by ID.
func (_c *SplitCreate) SetExpenseID(id int) *SplitCreate {
	_c.mutation.SetExpenseID(id)
	return _c
}

// SetExpense sets the "expense" edge to the Expense entity.
func (_c *SplitCreate) SetExpense(v *Expense) *SplitCreate {
	return _c.SetExpenseID(v.ID)
}

// Mutation returns the SplitMutation object of the builder.
func (_c *SplitCreate) Mutation() *SplitMutation {
	return _c.mutation
}

// Save creates the Split in the database.
func (_c *SplitCreate) Save(ctx context.Context) (*Split, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *SplitCreate) SaveX(ctx context.Context) *Split {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *SplitCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *SplitCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *SplitCreate) defaults() {
	if _, ok := _c.mutation.Settled(); !ok {
		v := split.DefaultSettled
		_c.mutation.SetSettled(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *SplitCreate) check() error {
	if _, ok := _c.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "Split.user_id"`)}
	}
	if _, ok := _c.mutation.Amount(); !ok {
		return &ValidationError{Name: "amount", err: errors.New(`ent: missing required field "Split.amount"`)}
	}
	if _, ok := _c.mutation.Settled(); !ok {
		return &ValidationError{Name: "settled", err: errors.New(`ent: missing required field "Split.settled"`)}
	}
	if len(_c.mutation.ExpenseIDs()) == 0 {
		return &ValidationError{Name: "expense", err: errors.New(`ent: missing required edge "Split.expense"`)}
	}
	return nil
}

func (_c *SplitCreate) sqlSave(ctx context.Context) (*Split, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *SplitCreate) createSpec() (*Split, *sqlgraph.CreateSpec) {
	var (
		_node = &Split{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(split.Table, sqlgraph.NewFieldSpec(split.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.UserID(); ok {
		_spec.SetField(split.FieldUserID, field.TypeString, value)
		_node.UserID = value
	}
	if value, ok := _c.mutation.Amount(); ok {
		_spec.SetField(split.FieldAmount, field.TypeInt64, value)
		_node.Amount = value
	}
	if value, ok := _c.mutation.Settled(); ok {
		_spec.SetField(split.FieldSettled, field.TypeBool, value)
		_node.Settled = value
	}
	if nodes := _c.mutation.ExpenseIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   split.ExpenseTable,
			Columns: []string{split.ExpenseColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(expense.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.expense_splits = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// SplitCreateBulk is the builder for creating many Split entities in bulk.
type SplitCreateBulk struct {
	config
	err      error
	builders []*SplitCreate
}

// Save creates the Split entities in the database.
func (_c *SplitCreateBulk) Save(ctx context.Context) ([]*Split, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Split, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*SplitMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *SplitCreateBulk) SaveX(ctx context.Context) []*Split {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *SplitCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *SplitCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
