// Code generated by ent, DO NOT EDIT.

package ent

import (
	"bill-bot/ent/expense"
	"bill-bot/ent/split"
	"fmt"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// Split is the model entity for the Split schema.
type Split struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// UserID holds the value of the "user_id" field.
	UserID string `json:"user_id,omitempty"`
	// Amount holds the value of the "amount" field.
	Amount int64 `json:"amount,omitempty"`
	// Settled holds the value of the "settled" field.
	Settled bool `json:"settled,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the SplitQuery when eager-loading is set.
	Edges          SplitEdges `json:"edges"`
	expense_splits *int
	selectValues   sql.SelectValues
}

// SplitEdges holds the relations/edges for other nodes in the graph.
type SplitEdges struct {
	// Expense holds the value of the expense edge.
	Expense *Expense `json:"expense,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// ExpenseOrErr returns the Expense value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e SplitEdges) ExpenseOrErr() (*Expense, error) {
	if e.Expense != nil {
		return e.Expense, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: expense.Label}
	}
	return nil, &NotLoadedError{edge: "expense"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Split) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case split.FieldSettled:
			values[i] = new(sql.NullBool)
		case split.FieldID, split.FieldAmount:
			values[i] = new(sql.NullInt64)
		case split.FieldUserID:
			values[i] = new(sql.NullString)
		case split.ForeignKeys[0]: // expense_splits
			values[i] = new(sql.NullInt64)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Split fields.
func (_m *Split) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case split.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case split.FieldUserID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field user_id", values[i])
			} else if value.Valid {
				_m.UserID = value.String
			}
		case split.FieldAmount:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field amount", values[i])
			} else if value.Valid {
				_m.Amount = value.Int64
			}
		case split.FieldSettled:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field settled", values[i])
			} else if value.Valid {
				_m.Settled = value.Bool
			}
		case split.ForeignKeys[0]:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for edge-field expense_splits", value)
			} else if value.Valid {
				_m.expense_splits = new(int)
				*_m.expense_splits = int(value.Int64)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Split.
// This includes values selected through modifiers, order, etc.
func (_m *Split) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryExpense queries the "expense" edge of the Split entity.
func (_m *Split) QueryExpense() *ExpenseQuery {
	return NewSplitClient(_m.config).QueryExpense(_m)
}

// Update returns a builder for updating this Split.
// Note that you need to call Split.Unwrap() before calling this method if this Split
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Split) Update() *SplitUpdateOne {
	return NewSplitClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Split entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Split) Unwrap() *Split {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Split is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Split) String() string {
	var builder strings.Builder
	builder.WriteString("Split(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("user_id=")
	builder.WriteString(_m.UserID)
	builder.WriteString(", ")
	builder.WriteString("amount=")
	builder.WriteString(fmt.Sprintf("%v", _m.Amount))
	builder.WriteString(", ")
	builder.WriteString("settled=")
	builder.WriteString(fmt.Sprintf("%v", _m.Settled))
	builder.WriteByte(')')
	return builder.String()
}

// Splits is a parsable slice of Split.
type Splits []*Split
