// Code generated by ent, DO NOT EDIT.

package ent

import (
	"bill-bot/ent/expense"
	"bill-bot/ent/predicate"
	"bill-bot/ent/split"
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// SplitUpdate is the builder for updating Split entities.
type SplitUpdate struct {
	config
	hooks    []Hook
	mutation *SplitMutation
}

// Where appends a list predicates to the SplitUpdate builder.
func (_u *SplitUpdate) Where(ps ...predicate.Split) *SplitUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *SplitUpdate) SetUserID(v string) *SplitUpdate {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *SplitUpdate) SetNillableUserID(v *string) *SplitUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetAmount sets the "amount" field.
func (_u *SplitUpdate) SetAmount(v int64) *SplitUpdate {
	_u.mutation.ResetAmount()
	_u.mutation.SetAmount(v)
	return _u
}

// SetNillableAmount sets the "amount" field if the given value is not nil.
func (_u *SplitUpdate) SetNillableAmount(v *int64) *SplitUpdate {
	if v != nil {
		_u.SetAmount(*v)
	}
	return _u
}

// AddAmount adds value to the "amount" field.
func (_u *SplitUpdate) AddAmount(v int64) *SplitUpdate {
	_u.mutation.AddAmount(v)
	return _u
}

// SetSettled sets the "settled" field.
func (_u *SplitUpdate) SetSettled(v bool) *SplitUpdate {
	_u.mutation.SetSettled(v)
	return _u
}

// SetNillableSettled sets the "settled" field if the given value is not nil.
func (_u *SplitUpdate) SetNillableSettled(v *bool) *SplitUpdate {
	if v != nil {
		_u.SetSettled(*v)
	}
	return _u
}

// SetExpenseID sets the "expense" edge to the Expense entity by ID.
func (_u *SplitUpdate) SetExpenseID(id int) *SplitUpdate {
	_u.mutation.SetExpenseID(id)
	return _u
}

// SetExpense sets the "expense" edge to the Expense entity.
func (_u *SplitUpdate) SetExpense(v *Expense) *SplitUpdate {
	return _u.SetExpenseID(v.ID)
}

// Mutation returns the SplitMutation object of the builder.
func (_u *SplitUpdate) Mutation() *SplitMutation {
	return _u.mutation
}

// ClearExpense clears the "expense" edge to the Expense entity.
func (_u *SplitUpdate) ClearExpense() *SplitUpdate {
	_u.mutation.ClearExpense()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *SplitUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *SplitUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *SplitUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *SplitUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *SplitUpdate) check() error {
	if _u.mutation.ExpenseCleared() && len(_u.mutation.ExpenseIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Split.expense"`)
	}
	return nil
}

func (_u *SplitUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(split.Table, split.Columns, sqlgraph.NewFieldSpec(split.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UserID(); ok {
		_spec.SetField(split.FieldUserID, field.TypeString, value)
	}
	if value, ok := _u.mutation.Amount(); ok {
		_spec.SetField(split.FieldAmount, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedAmount(); ok {
		_spec.AddField(split.FieldAmount, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.Settled(); ok {
		_spec.SetField(split.FieldSettled, field.TypeBool, value)
	}
	if _u.mutation.ExpenseCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   split.ExpenseTable,
			Columns: []string{split.ExpenseColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(expense.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ExpenseIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   split.ExpenseTable,
			Columns: []string{split.ExpenseColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(expense.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{split.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// SplitUpdateOne is the builder for updating a single Split entity.
type SplitUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *SplitMutation
}

// SetUserID sets the "user_id" field.
func (_u *SplitUpdateOne) SetUserID(v string) *SplitUpdateOne {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *SplitUpdateOne) SetNillableUserID(v *string) *SplitUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetAmount sets the "amount" field.
func (_u *SplitUpdateOne) SetAmount(v int64) *SplitUpdateOne {
	_u.mutation.ResetAmount()
	_u.mutation.SetAmount(v)
	return _u
}

// SetNillableAmount sets the "amount" field if the given value is not nil.
func (_u *SplitUpdateOne) SetNillableAmount(v *int64) *SplitUpdateOne {
	if v != nil {
		_u.SetAmount(*v)
	}
	return _u
}

// AddAmount adds value to the "amount" field.
func (_u *SplitUpdateOne) AddAmount(v int64) *SplitUpdateOne {
	_u.mutation.AddAmount(v)
	return _u
}

// SetSettled sets the "settled" field.
func (_u *SplitUpdateOne) SetSettled(v bool) *SplitUpdateOne {
	_u.mutation.SetSettled(v)
	return _u
}

// SetNillableSettled sets the "settled" field if the given value is not nil.
func (_u *SplitUpdateOne) SetNillableSettled(v *bool) *SplitUpdateOne {
	if v != nil {
		_u.SetSettled(*v)
	}
	return _u
}

// SetExpenseID sets the "expense" edge to the Expense entity by ID.
func (_u *SplitUpdateOne) SetExpenseID(id int) *SplitUpdateOne {
	_u.mutation.SetExpenseID(id)
	return _u
}

// SetExpense sets the "expense" edge to the Expense entity.
func (_u *SplitUpdateOne) SetExpense(v *Expense) *SplitUpdateOne {
	return _u.SetExpenseID(v.ID)
}

// Mutation returns the SplitMutation object of the builder.
func (_u *SplitUpdateOne) Mutation() *SplitMutation {
	return _u.mutation
}

// ClearExpense clears the "expense" edge to the Expense entity.
func (_u *SplitUpdateOne) ClearExpense() *SplitUpdateOne {
	_u.mutation.ClearExpense()
	return _u
}

// Where appends a list predicates to the SplitUpdate builder.
func (_u *SplitUpdateOne) Where(ps ...predicate.Split) *SplitUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *SplitUpdateOne) Select(field string, fields ...string) *SplitUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Split entity.
func (_u *SplitUpdateOne) Save(ctx context.Context) (*Split, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *SplitUpdateOne) SaveX(ctx context.Context) *Split {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *SplitUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *SplitUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *SplitUpdateOne) check() error {
	if _u.mutation.ExpenseCleared() && len(_u.mutation.ExpenseIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Split.expense"`)
	}
	return nil
}

func (_u *SplitUpdateOne) sqlSave(ctx context.Context) (_node *Split, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(split.Table, split.Columns, sqlgraph.NewFieldSpec(split.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Split.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, split.FieldID)
		for _, f := range fields {
			if !split.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != split.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UserID(); ok {
		_spec.SetField(split.FieldUserID, field.TypeString, value)
	}
	if value, ok := _u.mutation.Amount(); ok {
		_spec.SetField(split.FieldAmount, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedAmount(); ok {
		_spec.AddField(split.FieldAmount, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.Settled(); ok {
		_spec.SetField(split.FieldSettled, field.TypeBool, value)
	}
	if _u.mutation.ExpenseCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   split.ExpenseTable,
			Columns: []string{split.ExpenseColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(expense.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ExpenseIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   split.ExpenseTable,
			Columns: []string{split.ExpenseColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(expense.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Split{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{split.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
