// Code generated by ent, DO NOT EDIT.

package payment

import (
	"bill-bot/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.Payment {
	return predicate.Payment(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.Payment {
	return predicate.Payment(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.Payment {
	return predicate.Payment(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.Payment {
	return predicate.Payment(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.Payment {
	return predicate.Payment(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.Payment {
	return predicate.Payment(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.Payment {
	return predicate.Payment(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.Payment {
	return predicate.Payment(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.Payment {
	return predicate.Payment(sql.FieldLTE(FieldID, id))
}

// FromUserID applies equality check predicate on the "from_user_id" field. It's identical to FromUserIDEQ.
func FromUserID(v string) predicate.Payment {
	return predicate.Payment(sql.FieldEQ(FieldFromUserID, v))
}

// FromUserName applies equality check predicate on the "from_user_name" field. It's identical to FromUserNameEQ.
func FromUserName(v string) predicate.Payment {
	return predicate.Payment(sql.FieldEQ(FieldFromUserName, v))
}

// ToUserID applies equality check predicate on the "to_user_id" field. It's identical to ToUserIDEQ.
func ToUserID(v string) predicate.Payment {
	return predicate.Payment(sql.FieldEQ(FieldToUserID, v))
}

// ToUserName applies equality check predicate on the "to_user_name" field. It's identical to ToUserNameEQ.
func ToUserName(v string) predicate.Payment {
	return predicate.Payment(sql.FieldEQ(FieldToUserName, v))
}

// Amount applies equality check predicate on the "amount" field. It's identical to AmountEQ.
func Amount(v int64) predicate.Payment {
	return predicate.Payment(sql.FieldEQ(FieldAmount, v))
}

// Note applies equality check predicate on the "note" field. It's identical to NoteEQ.
func Note(v string) predicate.Payment {
	return predicate.Payment(sql.FieldEQ(FieldNote, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.Payment {
	return predicate.Payment(sql.FieldEQ(FieldCreatedAt, v))
}

// FromUserIDEQ applies the EQ predicate on the "from_user_id" field.
func FromUserIDEQ(v string) predicate.Payment {
	return predicate.Payment(sql.FieldEQ(FieldFromUserID, v))
}

// FromUserIDNEQ applies the NEQ predicate on the "from_user_id" field.
func FromUserIDNEQ(v string) predicate.Payment {
	return predicate.Payment(sql.FieldNEQ(FieldFromUserID, v))
}

// FromUserIDIn applies the In predicate on the "from_user_id" field.
func FromUserIDIn(vs ...string) predicate.Payment {
	return predicate.Payment(sql.FieldIn(FieldFromUserID, vs...))
}

// FromUserIDNotIn applies the NotIn predicate on the "from_user_id" field.
func FromUserIDNotIn(vs ...string) predicate.Payment {
	return predicate.Payment(sql.FieldNotIn(FieldFromUserID, vs...))
}

// FromUserIDGT applies the GT predicate on the "from_user_id" field.
func FromUserIDGT(v string) predicate.Payment {
	return predicate.Payment(sql.FieldGT(FieldFromUserID, v))
}

// FromUserIDGTE applies the GTE predicate on the "from_user_id" field.
func FromUserIDGTE(v string) predicate.Payment {
	return predicate.Payment(sql.FieldGTE(FieldFromUserID, v))
}

// FromUserIDLT applies the LT predicate on the "from_user_id" field.
func FromUserIDLT(v string) predicate.Payment {
	return predicate.Payment(sql.FieldLT(FieldFromUserID, v))
}

// FromUserIDLTE applies the LTE predicate on the "from_user_id" field.
func FromUserIDLTE(v string) predicate.Payment {
	return predicate.Payment(sql.FieldLTE(FieldFromUserID, v))
}

// FromUserIDContains applies the Contains predicate on the "from_user_id" field.
func FromUserIDContains(v string) predicate.Payment {
	return predicate.Payment(sql.FieldContains(FieldFromUserID, v))
}

// FromUserIDHasPrefix applies the HasPrefix predicate on the "from_user_id" field.
func FromUserIDHasPrefix(v string) predicate.Payment {
	return predicate.Payment(sql.FieldHasPrefix(FieldFromUserID, v))
}

// FromUserIDHasSuffix applies the HasSuffix predicate on the "from_user_id" field.
func FromUserIDHasSuffix(v string) predicate.Payment {
	return predicate.Payment(sql.FieldHasSuffix(FieldFromUserID, v))
}

// FromUserIDEqualFold applies the EqualFold predicate on the "from_user_id" field.
func FromUserIDEqualFold(v string) predicate.Payment {
	return predicate.Payment(sql.FieldEqualFold(FieldFromUserID, v))
}

// FromUserIDContainsFold applies the ContainsFold predicate on the "from_user_id" field.
func FromUserIDContainsFold(v string) predicate.Payment {
	return predicate.Payment(sql.FieldContainsFold(FieldFromUserID, v))
}

// FromUserNameEQ applies the EQ predicate on the "from_user_name" field.
func FromUserNameEQ(v string) predicate.Payment {
	return predicate.Payment(sql.FieldEQ(FieldFromUserName, v))
}

// FromUserNameNEQ applies the NEQ predicate on the "from_user_name" field.
func FromUserNameNEQ(v string) predicate.Payment {
	return predicate.Payment(sql.FieldNEQ(FieldFromUserName, v))
}

// FromUserNameIn applies the In predicate on the "from_user_name" field.
func FromUserNameIn(vs ...string) predicate.Payment {
	return predicate.Payment(sql.FieldIn(FieldFromUserName, vs...))
}

// FromUserNameNotIn applies the NotIn predicate on the "from_user_name" field.
func FromUserNameNotIn(vs ...string) predicate.Payment {
	return predicate.Payment(sql.FieldNotIn(FieldFromUserName, vs...))
}

// FromUserNameGT applies the GT predicate on the "from_user_name" field.
func FromUserNameGT(v string) predicate.Payment {
	return predicate.Payment(sql.FieldGT(FieldFromUserName, v))
}

// FromUserNameGTE applies the GTE predicate on the "from_user_name" field.
func FromUserNameGTE(v string) predicate.Payment {
	return predicate.Payment(sql.FieldGTE(FieldFromUserName, v))
}

// FromUserNameLT applies the LT predicate on the "from_user_name" field.
func FromUserNameLT(v string) predicate.Payment {
	return predicate.Payment(sql.FieldLT(FieldFromUserName, v))
}

// FromUserNameLTE applies the LTE predicate on the "from_user_name" field.
func FromUserNameLTE(v string) predicate.Payment {
	return predicate.Payment(sql.FieldLTE(FieldFromUserName, v))
}

// FromUserNameContains applies the Contains predicate on the "from_user_name" field.
func FromUserNameContains(v string) predicate.Payment {
	return predicate.Payment(sql.FieldContains(FieldFromUserName, v))
}

// FromUserNameHasPrefix applies the HasPrefix predicate on the "from_user_name" field.
func FromUserNameHasPrefix(v string) predicate.Payment {
	return predicate.Payment(sql.FieldHasPrefix(FieldFromUserName, v))
}

// FromUserNameHasSuffix applies the HasSuffix predicate on the "from_user_name" field.
func FromUserNameHasSuffix(v string) predicate.Payment {
	return predicate.Payment(sql.FieldHasSuffix(FieldFromUserName, v))
}

// FromUserNameEqualFold applies the EqualFold predicate on the "from_user_name" field.
func FromUserNameEqualFold(v string) predicate.Payment {
	return predicate.Payment(sql.FieldEqualFold(FieldFromUserName, v))
}

// FromUserNameContainsFold applies the ContainsFold predicate on the "from_user_name" field.
func FromUserNameContainsFold(v string) predicate.Payment {
	return predicate.Payment(sql.FieldContainsFold(FieldFromUserName, v))
}

// ToUserIDEQ applies the EQ predicate on the "to_user_id" field.
func ToUserIDEQ(v string) predicate.Payment {
	return predicate.Payment(sql.FieldEQ(FieldToUserID, v))
}

// ToUserIDNEQ applies the NEQ predicate on the "to_user_id" field.
func ToUserIDNEQ(v string) predicate.Payment {
	return predicate.Payment(sql.FieldNEQ(FieldToUserID, v))
}

// ToUserIDIn applies the In predicate on the "to_user_id" field.
func ToUserIDIn(vs ...string) predicate.Payment {
	return predicate.Payment(sql.FieldIn(FieldToUserID, vs...))
}

// ToUserIDNotIn applies the NotIn predicate on the "to_user_id" field.
func ToUserIDNotIn(vs ...string) predicate.Payment {
	return predicate.Payment(sql.FieldNotIn(FieldToUserID, vs...))
}

// ToUserIDGT applies the GT predicate on the "to_user_id" field.
func ToUserIDGT(v string) predicate.Payment {
	return predicate.Payment(sql.FieldGT(FieldToUserID, v))
}

// ToUserIDGTE applies the GTE predicate on the "to_user_id" field.
func ToUserIDGTE(v string) predicate.Payment {
	return predicate.Payment(sql.FieldGTE(FieldToUserID, v))
}

// ToUserIDLT applies the LT predicate on the "to_user_id" field.
func ToUserIDLT(v string) predicate.Payment {
	return predicate.Payment(sql.FieldLT(FieldToUserID, v))
}

// ToUserIDLTE applies the LTE predicate on the "to_user_id" field.
func ToUserIDLTE(v string) predicate.Payment {
	return predicate.Payment(sql.FieldLTE(FieldToUserID, v))
}

// ToUserIDContains applies the Contains predicate on the "to_user_id" field.
func ToUserIDContains(v string) predicate.Payment {
	return predicate.Payment(sql.FieldContains(FieldToUserID, v))
}

// ToUserIDHasPrefix applies the HasPrefix predicate on the "to_user_id" field.
func ToUserIDHasPrefix(v string) predicate.Payment {
	return predicate.Payment(sql.FieldHasPrefix(FieldToUserID, v))
}

// ToUserIDHasSuffix applies the HasSuffix predicate on the "to_user_id" field.
func ToUserIDHasSuffix(v string) predicate.Payment {
	return predicate.Payment(sql.FieldHasSuffix(FieldToUserID, v))
}

// ToUserIDEqualFold applies the EqualFold predicate on the "to_user_id" field.
func ToUserIDEqualFold(v string) predicate.Payment {
	return predicate.Payment(sql.FieldEqualFold(FieldToUserID, v))
}

// ToUserIDContainsFold applies the ContainsFold predicate on the "to_user_id" field.
func ToUserIDContainsFold(v string) predicate.Payment {
	return predicate.Payment(sql.FieldContainsFold(FieldToUserID, v))
}

// ToUserNameEQ applies the EQ predicate on the "to_user_name" field.
func ToUserNameEQ(v string) predicate.Payment {
	return predicate.Payment(sql.FieldEQ(FieldToUserName, v))
}

// ToUserNameNEQ applies the NEQ predicate on the "to_user_name" field.
func ToUserNameNEQ(v string) predicate.Payment {
	return predicate.Payment(sql.FieldNEQ(FieldToUserName, v))
}

// ToUserNameIn applies the In predicate on the "to_user_name" field.
func ToUserNameIn(vs ...string) predicate.Payment {
	return predicate.Payment(sql.FieldIn(FieldToUserName, vs...))
}

// ToUserNameNotIn applies the NotIn predicate on the "to_user_name" field.
func ToUserNameNotIn(vs ...string) predicate.Payment {
	return predicate.Payment(sql.FieldNotIn(FieldToUserName, vs...))
}

// ToUserNameGT applies the GT predicate on the "to_user_name" field.
func ToUserNameGT(v string) predicate.Payment {
	return predicate.Payment(sql.FieldGT(FieldToUserName, v))
}

// ToUserNameGTE applies the GTE predicate on the "to_user_name" field.
func ToUserNameGTE(v string) predicate.Payment {
	return predicate.Payment(sql.FieldGTE(FieldToUserName, v))
}

// ToUserNameLT applies the LT predicate on the "to_user_name" field.
func ToUserNameLT(v string) predicate.Payment {
	return predicate.Payment(sql.FieldLT(FieldToUserName, v))
}

// ToUserNameLTE applies the LTE predicate on the "to_user_name" field.
func ToUserNameLTE(v string) predicate.Payment {
	return predicate.Payment(sql.FieldLTE(FieldToUserName, v))
}

// ToUserNameContains applies the Contains predicate on the "to_user_name" field.
func ToUserNameContains(v string) predicate.Payment {
	return predicate.Payment(sql.FieldContains(FieldToUserName, v))
}

// ToUserNameHasPrefix applies the HasPrefix predicate on the "to_user_name" field.
func ToUserNameHasPrefix(v string) predicate.Payment {
	return predicate.Payment(sql.FieldHasPrefix(FieldToUserName, v))
}

// ToUserNameHasSuffix applies the HasSuffix predicate on the "to_user_name" field.
func ToUserNameHasSuffix(v string) predicate.Payment {
	return predicate.Payment(sql.FieldHasSuffix(FieldToUserName, v))
}

// ToUserNameEqualFold applies the EqualFold predicate on the "to_user_name" field.
func ToUserNameEqualFold(v string) predicate.Payment {
	return predicate.Payment(sql.FieldEqualFold(FieldToUserName, v))
}

// ToUserNameContainsFold applies the ContainsFold predicate on the "to_user_name" field.
func ToUserNameContainsFold(v string) predicate.Payment {
	return predicate.Payment(sql.FieldContainsFold(FieldToUserName, v))
}

// AmountEQ applies the EQ predicate on the "amount" field.
func AmountEQ(v int64) predicate.Payment {
	return predicate.Payment(sql.FieldEQ(FieldAmount, v))
}

// AmountNEQ applies the NEQ predicate on the "amount" field.
func AmountNEQ(v int64) predicate.Payment {
	return predicate.Payment(sql.FieldNEQ(FieldAmount, v))
}

// AmountIn applies the In predicate on the "amount" field.
func AmountIn(vs ...int64) predicate.Payment {
	return predicate.Payment(sql.FieldIn(FieldAmount, vs...))
}

// AmountNotIn applies the NotIn predicate on the "amount" field.
func AmountNotIn(vs ...int64) predicate.Payment {
	return predicate.Payment(sql.FieldNotIn(FieldAmount, vs...))
}

// AmountGT applies the GT predicate on the "amount" field.
func AmountGT(v int64) predicate.Payment {
	return predicate.Payment(sql.FieldGT(FieldAmount, v))
}

// AmountGTE applies the GTE predicate on the "amount" field.
func AmountGTE(v int64) predicate.Payment {
	return predicate.Payment(sql.FieldGTE(FieldAmount, v))
}

// AmountLT applies the LT predicate on the "amount" field.
func AmountLT(v int64) predicate.Payment {
	return predicate.Payment(sql.FieldLT(FieldAmount, v))
}

// AmountLTE applies the LTE predicate on the "amount" field.
func AmountLTE(v int64) predicate.Payment {
	return predicate.Payment(sql.FieldLTE(FieldAmount, v))
}

// NoteEQ applies the EQ predicate on the "note" field.
func NoteEQ(v string) predicate.Payment {
	return predicate.Payment(sql.FieldEQ(FieldNote, v))
}

// NoteNEQ applies the NEQ predicate on the "note" field.
func NoteNEQ(v string) predicate.Payment {
	return predicate.Payment(sql.FieldNEQ(FieldNote, v))
}

// NoteIn applies the In predicate on the "note" field.
func NoteIn(vs ...string) predicate.Payment {
	return predicate.Payment(sql.FieldIn(FieldNote, vs...))
}

// NoteNotIn applies the NotIn predicate on the "note" field.
func NoteNotIn(vs ...string) predicate.Payment {
	return predicate.Payment(sql.FieldNotIn(FieldNote, vs...))
}

// NoteGT applies the GT predicate on the "note" field.
func NoteGT(v string) predicate.Payment {
	return predicate.Payment(sql.FieldGT(FieldNote, v))
}

// NoteGTE applies the GTE predicate on the "note" field.
func NoteGTE(v string) predicate.Payment {
	return predicate.Payment(sql.FieldGTE(FieldNote, v))
}

// NoteLT applies the LT predicate on the "note" field.
func NoteLT(v string) predicate.Payment {
	return predicate.Payment(sql.FieldLT(FieldNote, v))
}

// NoteLTE applies the LTE predicate on the "note" field.
func NoteLTE(v string) predicate.Payment {
	return predicate.Payment(sql.FieldLTE(FieldNote, v))
}

// NoteContains applies the Contains predicate on the "note" field.
func NoteContains(v string) predicate.Payment {
	return predicate.Payment(sql.FieldContains(FieldNote, v))
}

// NoteHasPrefix applies the HasPrefix predicate on the "note" field.
func NoteHasPrefix(v string) predicate.Payment {
	return predicate.Payment(sql.FieldHasPrefix(FieldNote, v))
}

// NoteHasSuffix applies the HasSuffix predicate on the "note" field.
func NoteHasSuffix(v string) predicate.Payment {
	return predicate.Payment(sql.FieldHasSuffix(FieldNote, v))
}

// NoteIsNil applies the IsNil predicate on the "note" field.
func NoteIsNil() predicate.Payment {
	return predicate.Payment(sql.FieldIsNull(FieldNote))
}

// NoteNotNil applies the NotNil predicate on the "note" field.
func NoteNotNil() predicate.Payment {
	return predicate.Payment(sql.FieldNotNull(FieldNote))
}

// NoteEqualFold applies the EqualFold predicate on the "note" field.
func NoteEqualFold(v string) predicate.Payment {
	return predicate.Payment(sql.FieldEqualFold(FieldNote, v))
}

// NoteContainsFold applies the ContainsFold predicate on the "note" field.
func NoteContainsFold(v string) predicate.Payment {
	return predicate.Payment(sql.FieldContainsFold(FieldNote, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.Payment {
	return predicate.Payment(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.Payment {
	return predicate.Payment(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.Payment {
	return predicate.Payment(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.Payment {
	return predicate.Payment(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.Payment {
	return predicate.Payment(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.Payment {
	return predicate.Payment(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.Payment {
	return predicate.Payment(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.Payment {
	return predicate.Payment(sql.FieldLTE(FieldCreatedAt, v))
}

// HasLedger applies the HasEdge predicate on the "ledger" edge.
func HasLedger() predicate.Payment {
	return predicate.Payment(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, LedgerTable, LedgerColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasLedgerWith applies the HasEdge predicate on the "ledger" edge with a given conditions (other predicates).
func HasLedgerWith(preds ...predicate.Ledger) predicate.Payment {
	return predicate.Payment(func(s *sql.Selector) {
		step := newLedgerStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Payment) predicate.Payment {
	return predicate.Payment(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Payment) predicate.Payment {
	return predicate.Payment(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Payment) predicate.Payment {
	return predicate.Payment(sql.NotPredicates(p))
}
