// Code generated by ent, DO NOT EDIT.

package ledgermember

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the ledgermember type in the database.
	Label = "ledger_member"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldUserID holds the string denoting the user_id field in the database.
	FieldUserID = "user_id"
	// FieldUserName holds the string denoting the user_name field in the database.
	FieldUserName = "user_name"
	// FieldActive holds the string denoting the active field in the database.
	FieldActive = "active"
	// FieldJoinedAt holds the string denoting the joined_at field in the database.
	FieldJoinedAt = "joined_at"
	// EdgeLedger holds the string denoting the ledger edge name in mutations.
	EdgeLedger = "ledger"
	// Table holds the table name of the ledgermember in the database.
	Table = "ledger_members"
	// LedgerTable is the table that holds the ledger relation/edge.
	LedgerTable = "ledger_members"
	// LedgerInverseTable is the table name for the Ledger entity.
	// It exists in this package in order to avoid circular dependency with the "ledger" package.
	LedgerInverseTable = "ledgers"
	// LedgerColumn is the table column denoting the ledger relation/edge.
	LedgerColumn = "ledger_members"
)

// Columns holds all SQL columns for ledgermember fields.
var Columns = []string{
	FieldID,
	FieldUserID,
	FieldUserName,
	FieldActive,
	FieldJoinedAt,
}

// ForeignKeys holds the SQL foreign-keys that are owned by the "ledger_members"
// table and are not defined as standalone fields in the schema.
var ForeignKeys = []string{
	"ledger_members",
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	for i := range ForeignKeys {
		if column == ForeignKeys[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultActive holds the default value on creation for the "active" field.
	DefaultActive bool
	// DefaultJoinedAt holds the default value on creation for the "joined_at" field.
	DefaultJoinedAt func() time.Time
)

// OrderOption defines the ordering options for the LedgerMember queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByUserID orders the results by the user_id field.
func ByUserID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUserID, opts...).ToFunc()
}

// ByUserName orders the results by the user_name field.
func ByUserName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUserName, opts...).ToFunc()
}

// ByActive orders the results by the active field.
func ByActive(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldActive, opts...).ToFunc()
}

// ByJoinedAt orders the results by the joined_at field.
func ByJoinedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldJoinedAt, opts...).ToFunc()
}

// ByLedgerField orders the results by ledger field.
func ByLedgerField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newLedgerStep(), sql.OrderByField(field, opts...))
	}
}
func newLedgerStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(LedgerInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, LedgerTable, LedgerColumn),
	)
}
