// Code generated by ent, DO NOT EDIT.

package ledger

import (
	"bill-bot/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.Ledger {
	return predicate.Ledger(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.Ledger {
	return predicate.Ledger(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.Ledger {
	return predicate.Ledger(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.Ledger {
	return predicate.Ledger(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.Ledger {
	return predicate.Ledger(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.Ledger {
	return predicate.Ledger(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.Ledger {
	return predicate.Ledger(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.Ledger {
	return predicate.Ledger(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.Ledger {
	return predicate.Ledger(sql.FieldLTE(FieldID, id))
}

// ChannelID applies equality check predicate on the "channel_id" field. It's identical to ChannelIDEQ.
func ChannelID(v string) predicate.Ledger {
	return predicate.Ledger(sql.FieldEQ(FieldChannelID, v))
}

// GuildID applies equality check predicate on the "guild_id" field. It's identical to GuildIDEQ.
func GuildID(v string) predicate.Ledger {
	return predicate.Ledger(sql.FieldEQ(FieldGuildID, v))
}

// CategoryID applies equality check predicate on the "category_id" field. It's identical to CategoryIDEQ.
func CategoryID(v string) predicate.Ledger {
	return predicate.Ledger(sql.FieldEQ(FieldCategoryID, v))
}

// PinnedMessageID applies equality check predicate on the "pinned_message_id" field. It's identical to PinnedMessageIDEQ.
func PinnedMessageID(v string) predicate.Ledger {
	return predicate.Ledger(sql.FieldEQ(FieldPinnedMessageID, v))
}

// Active applies equality check predicate on the "active" field. It's identical to ActiveEQ.
func Active(v bool) predicate.Ledger {
	return predicate.Ledger(sql.FieldEQ(FieldActive, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.Ledger {
	return predicate.Ledger(sql.FieldEQ(FieldCreatedAt, v))
}

// ChannelIDEQ applies the EQ predicate on the "channel_id" field.
func ChannelIDEQ(v string) predicate.Ledger {
	return predicate.Ledger(sql.FieldEQ(FieldChannelID, v))
}

// ChannelIDNEQ applies the NEQ predicate on the "channel_id" field.
func ChannelIDNEQ(v string) predicate.Ledger {
	return predicate.Ledger(sql.FieldNEQ(FieldChannelID, v))
}

// ChannelIDIn applies the In predicate on the "channel_id" field.
func ChannelIDIn(vs ...string) predicate.Ledger {
	return predicate.Ledger(sql.FieldIn(FieldChannelID, vs...))
}

// ChannelIDNotIn applies the NotIn predicate on the "channel_id" field.
func ChannelIDNotIn(vs ...string) predicate.Ledger {
	return predicate.Ledger(sql.FieldNotIn(FieldChannelID, vs...))
}

// ChannelIDGT applies the GT predicate on the "channel_id" field.
func ChannelIDGT(v string) predicate.Ledger {
	return predicate.Ledger(sql.FieldGT(FieldChannelID, v))
}

// ChannelIDGTE applies the GTE predicate on the "channel_id" field.
func ChannelIDGTE(v string) predicate.Ledger {
	return predicate.Ledger(sql.FieldGTE(FieldChannelID, v))
}

// ChannelIDLT applies the LT predicate on the "channel_id" field.
func ChannelIDLT(v string) predicate.Ledger {
	return predicate.Ledger(sql.FieldLT(FieldChannelID, v))
}

// ChannelIDLTE applies the LTE predicate on the "channel_id" field.
func ChannelIDLTE(v string) predicate.Ledger {
	return predicate.Ledger(sql.FieldLTE(FieldChannelID, v))
}

// ChannelIDContains applies the Contains predicate on the "channel_id" field.
func ChannelIDContains(v string) predicate.Ledger {
	return predicate.Ledger(sql.FieldContains(FieldChannelID, v))
}

// ChannelIDHasPrefix applies the HasPrefix predicate on the "channel_id" field.
func ChannelIDHasPrefix(v string) predicate.Ledger {
	return predicate.Ledger(sql.FieldHasPrefix(FieldChannelID, v))
}

// ChannelIDHasSuffix applies the HasSuffix predicate on the "channel_id" field.
func ChannelIDHasSuffix(v string) predicate.Ledger {
	return predicate.Ledger(sql.FieldHasSuffix(FieldChannelID, v))
}

// ChannelIDEqualFold applies the EqualFold predicate on the "channel_id" field.
func ChannelIDEqualFold(v string) predicate.Ledger {
	return predicate.Ledger(sql.FieldEqualFold(FieldChannelID, v))
}

// ChannelIDContainsFold applies the ContainsFold predicate on the "channel_id" field.
func ChannelIDContainsFold(v string) predicate.Ledger {
	return predicate.Ledger(sql.FieldContainsFold(FieldChannelID, v))
}

// GuildIDEQ applies the EQ predicate on the "guild_id" field.
func GuildIDEQ(v string) predicate.Ledger {
	return predicate.Ledger(sql.FieldEQ(FieldGuildID, v))
}

// GuildIDNEQ applies the NEQ predicate on the "guild_id" field.
func GuildIDNEQ(v string) predicate.Ledger {
	return predicate.Ledger(sql.FieldNEQ(FieldGuildID, v))
}

// GuildIDIn applies the In predicate on the "guild_id" field.
func GuildIDIn(vs ...string) predicate.Ledger {
	return predicate.Ledger(sql.FieldIn(FieldGuildID, vs...))
}

// GuildIDNotIn applies the NotIn predicate on the "guild_id" field.
func GuildIDNotIn(vs ...string) predicate.Ledger {
	return predicate.Ledger(sql.FieldNotIn(FieldGuildID, vs...))
}

// GuildIDGT applies the GT predicate on the "guild_id" field.
func GuildIDGT(v string) predicate.Ledger {
	return predicate.Ledger(sql.FieldGT(FieldGuildID, v))
}

// GuildIDGTE applies the GTE predicate on the "guild_id" field.
func GuildIDGTE(v string) predicate.Ledger {
	return predicate.Ledger(sql.FieldGTE(FieldGuildID, v))
}

// GuildIDLT applies the LT predicate on the "guild_id" field.
func GuildIDLT(v string) predicate.Ledger {
	return predicate.Ledger(sql.FieldLT(FieldGuildID, v))
}

// GuildIDLTE applies the LTE predicate on the "guild_id" field.
func GuildIDLTE(v string) predicate.Ledger {
	return predicate.Ledger(sql.FieldLTE(FieldGuildID, v))
}

// GuildIDContains applies the Contains predicate on the "guild_id" field.
func GuildIDContains(v string) predicate.Ledger {
	return predicate.Ledger(sql.FieldContains(FieldGuildID, v))
}

// GuildIDHasPrefix applies the HasPrefix predicate on the "guild_id" field.
func GuildIDHasPrefix(v string) predicate.Ledger {
	return predicate.Ledger(sql.FieldHasPrefix(FieldGuildID, v))
}

// GuildIDHasSuffix applies the HasSuffix predicate on the "guild_id" field.
func GuildIDHasSuffix(v string) predicate.Ledger {
	return predicate.Ledger(sql.FieldHasSuffix(FieldGuildID, v))
}

// GuildIDEqualFold applies the EqualFold predicate on the "guild_id" field.
func GuildIDEqualFold(v string) predicate.Ledger {
	return predicate.Ledger(sql.FieldEqualFold(FieldGuildID, v))
}

// GuildIDContainsFold applies the ContainsFold predicate on the "guild_id" field.
func GuildIDContainsFold(v string) predicate.Ledger {
	return predicate.Ledger(sql.FieldContainsFold(FieldGuildID, v))
}

// CategoryIDEQ applies the EQ predicate on the "category_id" field.
func CategoryIDEQ(v string) predicate.Ledger {
	return predicate.Ledger(sql.FieldEQ(FieldCategoryID, v))
}

// CategoryIDNEQ applies the NEQ predicate on the "category_id" field.
func CategoryIDNEQ(v string) predicate.Ledger {
	return predicate.Ledger(sql.FieldNEQ(FieldCategoryID, v))
}

// CategoryIDIn applies the In predicate on the "category_id" field.
func CategoryIDIn(vs ...string) predicate.Ledger {
	return predicate.Ledger(sql.FieldIn(FieldCategoryID, vs...))
}

// CategoryIDNotIn applies the NotIn predicate on the "category_id" field.
func CategoryIDNotIn(vs ...string) predicate.Ledger {
	return predicate.Ledger(sql.FieldNotIn(FieldCategoryID, vs...))
}

// CategoryIDGT applies the GT predicate on the "category_id" field.
func CategoryIDGT(v string) predicate.Ledger {
	return predicate.Ledger(sql.FieldGT(FieldCategoryID, v))
}

// CategoryIDGTE applies the GTE predicate on the "category_id" field.
func CategoryIDGTE(v string) predicate.Ledger {
	return predicate.Ledger(sql.FieldGTE(FieldCategoryID, v))
}

// CategoryIDLT applies the LT predicate on the "category_id" field.
func CategoryIDLT(v string) predicate.Ledger {
	return predicate.Ledger(sql.FieldLT(FieldCategoryID, v))
}

// CategoryIDLTE applies the LTE predicate on the "category_id" field.
func CategoryIDLTE(v string) predicate.Ledger {
	return predicate.Ledger(sql.FieldLTE(FieldCategoryID, v))
}

// CategoryIDContains applies the Contains predicate on the "category_id" field.
func CategoryIDContains(v string) predicate.Ledger {
	return predicate.Ledger(sql.FieldContains(FieldCategoryID, v))
}

// CategoryIDHasPrefix applies the HasPrefix predicate on the "category_id" field.
func CategoryIDHasPrefix(v string) predicate.Ledger {
	return predicate.Ledger(sql.FieldHasPrefix(FieldCategoryID, v))
}

// CategoryIDHasSuffix applies the HasSuffix predicate on the "category_id" field.
func CategoryIDHasSuffix(v string) predicate.Ledger {
	return predicate.Ledger(sql.FieldHasSuffix(FieldCategoryID, v))
}

// CategoryIDIsNil applies the IsNil predicate on the "category_id" field.
func CategoryIDIsNil() predicate.Ledger {
	return predicate.Ledger(sql.FieldIsNull(FieldCategoryID))
}

// CategoryIDNotNil applies the NotNil predicate on the "category_id" field.
func CategoryIDNotNil() predicate.Ledger {
	return predicate.Ledger(sql.FieldNotNull(FieldCategoryID))
}

// CategoryIDEqualFold applies the EqualFold predicate on the "category_id" field.
func CategoryIDEqualFold(v string) predicate.Ledger {
	return predicate.Ledger(sql.FieldEqualFold(FieldCategoryID, v))
}

// CategoryIDContainsFold applies the ContainsFold predicate on the "category_id" field.
func CategoryIDContainsFold(v string) predicate.Ledger {
	return predicate.Ledger(sql.FieldContainsFold(FieldCategoryID, v))
}

// PinnedMessageIDEQ applies the EQ predicate on the "pinned_message_id" field.
func PinnedMessageIDEQ(v string) predicate.Ledger {
	return predicate.Ledger(sql.FieldEQ(FieldPinnedMessageID, v))
}

// PinnedMessageIDNEQ applies the NEQ predicate on the "pinned_message_id" field.
func PinnedMessageIDNEQ(v string) predicate.Ledger {
	return predicate.Ledger(sql.FieldNEQ(FieldPinnedMessageID, v))
}

// PinnedMessageIDIn applies the In predicate on the "pinned_message_id" field.
func PinnedMessageIDIn(vs ...string) predicate.Ledger {
	return predicate.Ledger(sql.FieldIn(FieldPinnedMessageID, vs...))
}

// PinnedMessageIDNotIn applies the NotIn predicate on the "pinned_message_id" field.
func PinnedMessageIDNotIn(vs ...string) predicate.Ledger {
	return predicate.Ledger(sql.FieldNotIn(FieldPinnedMessageID, vs...))
}

// PinnedMessageIDGT applies the GT predicate on the "pinned_message_id" field.
func PinnedMessageIDGT(v string) predicate.Ledger {
	return predicate.Ledger(sql.FieldGT(FieldPinnedMessageID, v))
}

// PinnedMessageIDGTE applies the GTE predicate on the "pinned_message_id" field.
func PinnedMessageIDGTE(v string) predicate.Ledger {
	return predicate.Ledger(sql.FieldGTE(FieldPinnedMessageID, v))
}

// PinnedMessageIDLT applies the LT predicate on the "pinned_message_id" field.
func PinnedMessageIDLT(v string) predicate.Ledger {
	return predicate.Ledger(sql.FieldLT(FieldPinnedMessageID, v))
}

// PinnedMessageIDLTE applies the LTE predicate on the "pinned_message_id" field.
func PinnedMessageIDLTE(v string) predicate.Ledger {
	return predicate.Ledger(sql.FieldLTE(FieldPinnedMessageID, v))
}

// PinnedMessageIDContains applies the Contains predicate on the "pinned_message_id" field.
func PinnedMessageIDContains(v string) predicate.Ledger {
	return predicate.Ledger(sql.FieldContains(FieldPinnedMessageID, v))
}

// PinnedMessageIDHasPrefix applies the HasPrefix predicate on the "pinned_message_id" field.
func PinnedMessageIDHasPrefix(v string) predicate.Ledger {
	return predicate.Ledger(sql.FieldHasPrefix(FieldPinnedMessageID, v))
}

// PinnedMessageIDHasSuffix applies the HasSuffix predicate on the "pinned_message_id" field.
func PinnedMessageIDHasSuffix(v string) predicate.Ledger {
	return predicate.Ledger(sql.FieldHasSuffix(FieldPinnedMessageID, v))
}

// PinnedMessageIDIsNil applies the IsNil predicate on the "pinned_message_id" field.
func PinnedMessageIDIsNil() predicate.Ledger {
	return predicate.Ledger(sql.FieldIsNull(FieldPinnedMessageID))
}

// PinnedMessageIDNotNil applies the NotNil predicate on the "pinned_message_id" field.
func PinnedMessageIDNotNil() predicate.Ledger {
	return predicate.Ledger(sql.FieldNotNull(FieldPinnedMessageID))
}

// PinnedMessageIDEqualFold applies the EqualFold predicate on the "pinned_message_id" field.
func PinnedMessageIDEqualFold(v string) predicate.Ledger {
	return predicate.Ledger(sql.FieldEqualFold(FieldPinnedMessageID, v))
}

// PinnedMessageIDContainsFold applies the ContainsFold predicate on the "pinned_message_id" field.
func PinnedMessageIDContainsFold(v string) predicate.Ledger {
	return predicate.Ledger(sql.FieldContainsFold(FieldPinnedMessageID, v))
}

// ActiveEQ applies the EQ predicate on the "active" field.
func ActiveEQ(v bool) predicate.Ledger {
	return predicate.Ledger(sql.FieldEQ(FieldActive, v))
}

// ActiveNEQ applies the NEQ predicate on the "active" field.
func ActiveNEQ(v bool) predicate.Ledger {
	return predicate.Ledger(sql.FieldNEQ(FieldActive, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.Ledger {
	return predicate.Ledger(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.Ledger {
	return predicate.Ledger(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.Ledger {
	return predicate.Ledger(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.Ledger {
	return predicate.Ledger(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.Ledger {
	return predicate.Ledger(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.Ledger {
	return predicate.Ledger(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.Ledger {
	return predicate.Ledger(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.Ledger {
	return predicate.Ledger(sql.FieldLTE(FieldCreatedAt, v))
}

// HasExpenses applies the HasEdge predicate on the "expenses" edge.
func HasExpenses() predicate.Ledger {
	return predicate.Ledger(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, ExpensesTable, ExpensesColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasExpensesWith applies the HasEdge predicate on the "expenses" edge with a given conditions (other predicates).
func HasExpensesWith(preds ...predicate.Expense) predicate.Ledger {
	return predicate.Ledger(func(s *sql.Selector) {
		step := newExpensesStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasPayments applies the HasEdge predicate on the "payments" edge.
func HasPayments() predicate.Ledger {
	return predicate.Ledger(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, PaymentsTable, PaymentsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasPaymentsWith applies the HasEdge predicate on the "payments" edge with a given conditions (other predicates).
func HasPaymentsWith(preds ...predicate.Payment) predicate.Ledger {
	return predicate.Ledger(func(s *sql.Selector) {
		step := newPaymentsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasMembers applies the HasEdge predicate on the "members" edge.
func HasMembers() predicate.Ledger {
	return predicate.Ledger(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, MembersTable, MembersColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasMembersWith applies the HasEdge predicate on the "members" edge with a given conditions (other predicates).
func HasMembersWith(preds ...predicate.LedgerMember) predicate.Ledger {
	return predicate.Ledger(func(s *sql.Selector) {
		step := newMembersStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Ledger) predicate.Ledger {
	return predicate.Ledger(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Ledger) predicate.Ledger {
	return predicate.Ledger(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Ledger) predicate.Ledger {
	return predicate.Ledger(sql.NotPredicates(p))
}
