// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Expense is the predicate function for expense builders.
type Expense func(*sql.Selector)

// Ledger is the predicate function for ledger builders.
type Ledger func(*sql.Selector)

// LedgerMember is the predicate function for ledgermember builders.
type LedgerMember func(*sql.Selector)

// Payment is the predicate function for payment builders.
type Payment func(*sql.Selector)

// Split is the predicate function for split builders.
type Split func(*sql.Selector)
